# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{subtitle_it}
  s.version = "1.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2011-05-30}
  s.default_executable = %q{subtitle_it}
  s.description = %q{Download, edit and create subtitles. Supports various formats.}
  s.email = %q{x@nofxx.com}
  s.executables = ["subtitle_it"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".rspec",
    "History.txt",
    "License.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/subtitle_it",
    "config/hoe.rb",
    "config/requirements.rb",
    "lib/subtitle_it.rb",
    "lib/subtitle_it/bin.rb",
    "lib/subtitle_it/fixes.rb",
    "lib/subtitle_it/formats/ass.rb",
    "lib/subtitle_it/formats/mpl.rb",
    "lib/subtitle_it/formats/rsb.rb",
    "lib/subtitle_it/formats/srt.rb",
    "lib/subtitle_it/formats/sub.rb",
    "lib/subtitle_it/formats/xml.rb",
    "lib/subtitle_it/formats/yml.rb",
    "lib/subtitle_it/generator.rb",
    "lib/subtitle_it/languages.rb",
    "lib/subtitle_it/movie.rb",
    "lib/subtitle_it/movie_hasher.rb",
    "lib/subtitle_it/platform_endl.rb",
    "lib/subtitle_it/subdown.rb",
    "lib/subtitle_it/subline.rb",
    "lib/subtitle_it/substyle.rb",
    "lib/subtitle_it/subtime.rb",
    "lib/subtitle_it/subtitle.rb",
    "lib/subtitle_it/version.rb",
    "script/console",
    "script/destroy",
    "script/generate",
    "script/txt2html",
    "spec/fixtures/godfather.srt",
    "spec/fixtures/huge.ass",
    "spec/fixtures/movie.xml",
    "spec/fixtures/movie.yml",
    "spec/fixtures/pseudo.rsb",
    "spec/fixtures/pulpfiction.sub",
    "spec/fixtures/puplfiction.mpl",
    "spec/fixtures/sincity.yml",
    "spec/spec_helper.rb",
    "spec/subtitle_it/bin_spec.rb",
    "spec/subtitle_it/fixes_spec.rb",
    "spec/subtitle_it/formats/ass_spec.rb",
    "spec/subtitle_it/formats/mpl_spec.rb",
    "spec/subtitle_it/formats/rsb_spec.rb",
    "spec/subtitle_it/formats/srt_spec.rb",
    "spec/subtitle_it/formats/sub_spec.rb",
    "spec/subtitle_it/formats/xml_spec.rb",
    "spec/subtitle_it/formats/yml_spec.rb",
    "spec/subtitle_it/generator_spec.rb",
    "spec/subtitle_it/movie_hasher_spec.rb",
    "spec/subtitle_it/movie_spec.rb",
    "spec/subtitle_it/subdown_spec.rb",
    "spec/subtitle_it/subline_spec.rb",
    "spec/subtitle_it/substyle_spec.rb",
    "spec/subtitle_it/subtime_spec.rb",
    "spec/subtitle_it/subtitle_spec.rb",
    "spec/subtitle_it_spec.rb",
    "subtitle_it.gemspec",
    "tasks/deployment.rake",
    "tasks/environment.rake",
    "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/nofxx/subtitle_it}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Download, edit and create subtitles.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

