{1025}{1115}You always say that.|The same thing every time.
{1118}{1177}"l'm through, never again,|too dangerous."
{1180}{1270}I know that's what I always say.|I'm always right too.
{1274}{1364}- You forget about it in a day or two.|- The days of me forgetting are over.
{1368}{1428}The days of me remembering|have just begun.
{1430}{1490}You know, when you go on like this,|what you sound like ?
{1493}{1583}- I sound like a sensible fuckin' man.|- You sound like a duck.
{1587}{1707}- Quack, quack, quack.|- Take heart, 'cause you're never
{1712}{1802}Since I'm never gonna|do it again, you're never
{1806}{1956}- After tonight ?|- Correct. I got all tonight to quack.
{1962}{2022}- Can I get anyone more coffee ?|- Oh, yes !
{2087}{2176}- Thank you.|- You're welcome.
{2180}{2270}I mean, the way it is now,
{2274}{2334}you're takin' the same risk|as when you rob a bank.
{2336}{2396}Takin' more of a risk.|Banks are easier.
{2399}{2489}Federal banks ain't supposed to stop you|in any way during a robbery.
{2493}{2643}They're insured. Why should|they give a fuck ? I don't even
{2649}{2739}Heard about this one bloke, he walks|into a bank with a portable phone.
{2743}{2833}He gives the phone to a teller.|The bloke on the other end says,
{2837}{2927}"We got this guy's little girl.|If you don't give him all your
{2931}{3021}- Did it work ?|- Fuckin' right it worked.
{3025}{3204}Knucklehead walks into a bank|with a telephone. Not a pistol,
{3211}{3331}- Cleans the place out.|They don't lift a fuckin' finger.
{3336}{3456}There probably never was|a little girl. The point of
{3462}{3552}The point of the story is they|robbed a bank with a telephone.
{3555}{3645}- You want to rob banks ?|- I'm not saying I wanna rob banks.
{3649}{3709}I'm illustrating if we did, it'd be|easier than what we've been doing.
{3712}{3832}-No more liquor stores ?|-What've we been talkin' about ?
{3837}{3927}Besides, it ain't the giggle|it used to be. There's too many
{3931}{3991}Vietnamese, Koreans,|don't even speak fuckin' English.
{3993}{4053}You tell 'em empty out|the register, they don't know
{4056}{4116}They make it too personal.
{4119}{4239}- We keep on, one of these gook|fuckers gonna make us kill him.
{4244}{4393}I don't want to either.|But they'll probably put us
{4399}{4429}And if it's not the gooks,
{4462}{4522}it's these old fuckin' Jews who've owned|the store for 15 fucking generations.
{4524}{4644}You got Grandpa lrving sitting|behind the counter with
{4649}{4709}Try walkin' into one of those places|with nothing but a phone.
{4712}{4772}See how far that gets you.|Forget it.
{4774}{4864}- We're out of it.|- Well, what then, day jobs ?
{4868}{4928}- Not in this life.|- What then ?
{4993}{5053}Garçon, coffee !
{5056}{5146}This place.
{5181}{5271}Garçon means boy.
{5368}{5458}This place ?|A coffee shop ?
{5462}{5552}What's wrong with that ?
{5555}{5645}Nobody ever robs restaurants.|Why not ?
{5681}{5741}Bars, liquor stores,
{5743}{5863}gas stations; you get your head|blown off stickin' up one of them.
{5868}{5988}Restaurants, on the other hand,|you catch with their pants down.
{5993}{6083}They're not expectin' to get robbed.|Not as expectin' anyway.
{6087}{6237}- I bet you could cut down on the|hero factor in a place like this.
{6244}{6333}Same as banks,|these places are insured.
{6336}{6396}Manager.|He don't give a fuck.
{6399}{6489}They're just trying to get you out|before you start pluggin' the diners.
{6493}{6613}Waitresses. Fuckin' forget it.|No way they're takin' a bullet
{6618}{6708}Busboys. Some wetback gettin'|paid $1.50 an hour...
{6712}{6772}really give a fuck|you're stealin' from the owner ?
{6774}{6864}Customers sittin' there|with food in their mouths,
{6868}{7018}One minute, they're havin'|a Denver omelet, the next, someone
{7025}{7175}See, I got the idea the last|liquor store we stuck up, remember ?
{7181}{7241}- All the customers kept comin' in.|- Yeah.
{7244}{7364}You got the idea|of takin' their wallets.
{7369}{7458}- Thank you.|- Made more from the wallets
{7462}{7552}- Yes, we did.|- A lot of people come to restaurants.
{7555}{7645}- A lot of wallets.|- Pretty smart, huh ?
{7649}{7709}Pretty smart.
{7774}{7864}I'm ready. Let's do it.|Right now, right here.
{7868}{7988}- Come on.|- All right. Same as
{7993}{8083}You're crowd control.|I'll handle the employees.
{8244}{8334}- I love you, Pumpkin.|- I love you, Honey Bunny.
{8369}{8428}Everybody be cool !|This is a robbery !
{8430}{8520}Any of you fucking pricks move,
{8524}{8644}and I'll execute|every motherfuckin' last one of you.
{8649}{8649}and I'll execute|every motherfuckin' last one of you.
{11993}{12053}- Jungle boogie|- Get down with the boogie
{12056}{12116}- Jungle boogie|- Get it on
{12119}{12179}- Jungle boogie|- Get down with the boogie
{12181}{12271}- Jungle boogie|- Get it on
{12275}{12335}- Jungle boogie|- Get up with the boogie
{12338}{12398}- Jungle boogie|- Get up with the get down
{12400}{12460}- Jungle boogie|- Get down and boogie
{12463}{12553}- Jungle boogie|- Shake it around
{12774}{12894}- Okay, so tell me again|about the hash bars.
{12900}{12960}- Hash is legal there, right ?|- It's legal, but it ain't 100% legal.
{12993}{13113}You just can't walk into a restaurant,|roll a joint and start puffin' away.
{13119}{13209}I mean, they want you to smoke in|your home or certain designated places.
{13212}{13302}- Those are hash bars ?|- Yeah. It breaks down like this.
{13306}{13366}It's legal to buy it.|It's legal to own it.
{13369}{13459}And if you're the proprietor|of a hash bar, it's legal to sell it.
{13463}{13613}It's illegal to carry it,|but-but that doesn't matter,
{13619}{13738}If you get stopped by a cop|in Amsterdam, it's illegal
{13743}{13863}- I mean, that's a right the cops|in Amsterdam don't have.
{13868}{13928}That's all there is to it.|I'm fuckin' goin'.
{13931}{14021}I know, baby.|You'd dig it the most.
{14025}{14115}- But you know what the funniest thing|about Europe is ?
{14119}{14239}It's the little differences.|I mean, they got the same shit
{14244}{14334}- but it's just there,|it's a little different.
{14338}{14428}You can walk into a movie theater|in Amsterdam and buy a beer.
{14431}{14551}And I don't mean just like no paper cup.|I'm talkin' about a glass of beer.
{14557}{14647}And in Paris, you can buy|a beer in McDonald's.
{14681}{14771}a Quarter-Pounder|with Cheese in Paris ?
{14774}{14834}They don't call it|a Quarter-Pounder with Cheese ?
{14837}{14927}They got the metric system.|They wouldn't know what the fuck
{14931}{15051}- What do they call it ?|- They call it a Royale with Cheese.
{15056}{15086}- Royale with Cheese.|- That's right.
{15087}{15147}What do they call a Big Mac ?
{15150}{15240}Big Mac's a Big Mac,|but they call it Le Big Mac.
{15244}{15334}Le Big Mac.
{15338}{15458}- What do they call a Whopper ?|- I don't know. I didn't
{15463}{15583}- You know what they put on French fries|in Holland instead of ketchup ?
{15588}{15678}- Mayonnaise.|- Goddamn !
{15682}{15801}- I seen 'em do it, man.|They fuckin' drown 'em in that shit.
{15868}{15988}We should have shotguns|for this kind of deal.
{16056}{16146}- How many up there ?|- Three or four.
{16150}{16270}- That's countin' our guy ?|- Not sure.
{16275}{16365}- So that means that it could be|up to five guys up there ?
{16369}{16429}We should have|fuckin' shotguns.
{16431}{16521}- What's her name ?|- Mia.
{16525}{16645}- Mia. How did Marsellus and her meet ?|- I don't know.
{16650}{16769}However people meet people.|She used to be a actress.
{16774}{16834}Oh, really ?|She do anything I'd have seen ?
{16837}{16957}- I think her biggest deal|was she starred in a pilot.
{16962}{17082}- Well, you know the shows on TV ?|- I don't watch TV.
{17087}{17177}Yeah, but you are aware that there|is an invention called television,
{17181}{17271}- and on this invention|they show shows, right ?
{17275}{17425}The way they pick TV shows is they make|one show. That show's called a pilot.
{17431}{17521}Then they show that one show|to the people who pick shows...
{17525}{17585}and on the strength of that|one show, they decide if
{17588}{17738}Some get chosen and|become television programs.
{17744}{17833}She starred in one of the ones|that became nothing.
{17837}{17927}You remember|Antwan Rockamora ?
{17931}{18021}Half-black, half-Samoan.|Used to call him "Tony Rocky Horror."
{18056}{18146}- Yeah, maybe. Fat, right ?|- I wouldn't go so far as to
{18150}{18240}I mean, he got a weight problem.|What's a nigger gonna do ? He's Samoan.
{18244}{18364}- I think I know who you mean.|What about him ?
{18369}{18489}Word 'round the campfire is|it was on account of
{18744}{18863}- So what he'd do ? Fuck her ?|- No, no, no, no, no. Nothin' that bad.
{18868}{18958}- Well, then what then ?|- He gave her a foot massage.
{19025}{19115}A foot massage ?
{19119}{19179}- That's it ?|- Mm-hmm.
{19181}{19241}Then what'd Marsellus do ?
{19244}{19334}Sent a couple cats over to his place.|They took him out on his patio.
{19338}{19458}Threw his ass over the balcony.|Nigger fell four stories.
{19463}{19583}He had a little garden down|at the bottom enclosed in glass,
{19588}{19648}Nigger fell through that.
{19650}{19740}Since then, he kind of|developed a speech impediment.
{19776}{19866}- That's a damn shame.|- Hmm.
{19994}{20114}- But still, you play|with matches, you get burned.
{20119}{20239}You don't be givin' Marsellus Wallace's|new bride a foot massage.
{20244}{20304}You don't think he overreacted ?
{20306}{20456}Antwan didn't expect Marsellus|to react the way he did,
{20463}{20583}It was a foot massage.|A foot massage is nothin'.
{20588}{20708}It's laying your hands in a familiar way|on Marsellus's new wife.
{20713}{20833}I mean, is it as bad as eatin'|her pussy out ? No, but it's
{20838}{20898}Whoa, stop right there.|Eatin' the bitch out...
{20901}{20990}and givin' the bitch a foot massage|ain't even the same fucking thing.
{20994}{21114}- It's not. It's the same ballpark.|- Ain't no fuckin' ballpark neither.
{21119}{21209}Now, look, maybe your method|of massage differs from mine.
{21212}{21302}But touchin' his wife's feet|and sticking your tongue
{21306}{21456}ain't the same fuckin' ballpark;|it ain't the same league;
{21463}{21553}- Foot massages don't mean shit !|- Have you ever given a foot massage ?
{21557}{21647}Don't be tellin' me about foot massages.
{21650}{21740}- I'm the foot fuckin' master.|- You given a lot of them ?
{21744}{21864}Shit, yeah !|Got my technique down and everything.
{21869}{21958}Would you give a guy|a foot massage ?
{21994}{22084}- Fuck you.
{22087}{22177}- You give 'em a lot ?|- Fuck you.
{22181}{22271}- You know, I'm kind of tired.|I could use a foot massage.
{22275}{22365}You best back off.|I'm gettin' a little pissed here.
{22400}{22490}- This is the door.|- Yeah, it is.
{22557}{22647}What time you got ?
{22650}{22710}7:22 in the a.m.
{22713}{22803}No, it ain't quite time yet.|Come on. Let's hang back.
{23056}{23146}Look, just 'cause I wouldn't give no man|a foot massage don't make it right...
{23150}{23240}for Marsellus to throw|Antwan off a building into
{23244}{23334}fuckin' up the way the nigger talks;|that shit ain't right.
{23338}{23458}Motherfucker do that shit to me,|he better paralyze my ass,
{23463}{23613}I ain't sayin' it's right,|but you sayin' a massage don't mean
{23619}{23739}Now, look, I've given a million|ladies a million foot massages,
{23776}{23866}We act like they don't,|but they do. That's what's
{23869}{23929}There's a sensuous thing goin' on...
{23932}{24022}where you don't talk about it,|but you know it and she knows it.
{24026}{24175}Fuckin' Marsellus knew it. And Antwan|should've fuckin' better known better.
{24181}{24331}That's his fuckin' wife, man.|This ain't a man with a sense
{24338}{24398}You know what I'm sayin' ?
{24400}{24460}It's an interestin' point.
{24463}{24523}Come on.|Let's get into character.
{24744}{24804}- What's her name again ?|- Mia.
{24807}{24897}- Mia.|- Why you so interested
{24901}{25051}He's goin' out of town, Florida.|And he asked me if I'd take care
{25057}{25176}- Take care of her ?|- No, man. Just take her out.
{25181}{25271}Show her a good time.|Make sure she don't get lonely.
{25275}{25335}You're gonna be takin'|Mia Wallace out on a date ?
{25369}{25429}It is not a date.
{25432}{25552}It's just like if you were|gonna take your buddy's wife
{25557}{25677}- It's just good company, that's all.
{25776}{25926}- It's not a date.|It's definitely not a date.
{26120}{26239}Hey, kids.|How you boys doin' ?
{26244}{26304}Hey, keep chillin'.
{26494}{26584}You know who we are ?
{26588}{26708}We're associates of your|business partner, Marsellus Wallace.
{26713}{26803}You do remember|your business partner, don't you ?
{26869}{26959}Now, let me take|a wild guess here.
{27026}{27116}- You're Brett, right ?|- Yeah.
{27120}{27239}I thought so. You remember|your business partner Marsellus Wallace,
{27244}{27304}don't ya, Brett ?
{27306}{27366}Yeah, I remember.
{27369}{27489}Good. Looks like me and Vincent|caught you boys at breakfast.
{27494}{27584}Sorry about that.|Whatcha havin' ?
{27588}{27648}Hamburgers.
{27650}{27770}Hamburgers ! The cornerstone|of any nutritious breakfast.
{27807}{27867}What kind of hamburgers ?
{27869}{27929}- Uh, ch-cheeseburgers.|- No, no, no.
{27932}{28022}Where'd you get 'em ?|McDonald's, Wendy's, Jack-in-the-Box ?
{28026}{28116}- Where ?|- Uh, Big Kahuna Burger.
{28120}{28209}Big Kahuna Burger !|That's that Hawaiian burger joint.
{28213}{28333}I hear they got some tasty burgers.|I ain't never had one myself.
{28338}{28398}They're-- They're good.
{28400}{28490}You mind if I try|one of yours ?
{28494}{28554}- This is yours here, right ?|- Yeah.
{28807}{28867}Mmmm.
{28869}{28959}This is a tasty burger !|Vincent !
{28963}{29023}You ever had|a Big Kahuna burger ?
{29057}{29147}Want a bite ?|They're real tasty.
{29151}{29241}- I ain't hungry.|- Well, if you like burgers,
{29245}{29364}Me, I can't usually get 'em|'cause my girlfriend's a vegetarian,
{29369}{29459}which pretty much makes me|a vegetarian.
{29463}{29553}But I do love the taste|of a good burger. Mmmm.
{29557}{29677}You know what they call|a Quarter-Pounder with Cheese
{29713}{29773}- No.|- Tell 'em, Vincent.
{29776}{29866}- A Royale with Cheese.|- A Royale with Cheese.
{29901}{29991}You know why they call it that ?
{29995}{30085}Uh, because of|the metric system ?
{30120}{30210}Check out the big brain|on Brett !
{30214}{30303}You're a smart motherfucker.|That's right. The metric system.
{30400}{30460}- What's in this ?|- Sprite.
{30463}{30523}Sprite. Good.
{30525}{30615}You mind if I have some of your|tasty beverage to wash this down with ?
{30619}{30709}Go right ahead.
{31057}{31147}That hit the spot.
{31151}{31271}You. Flock of Seagulls.|You know why we're here ?
{31276}{31365}- Why don't you tell my man|Vince here where you got the shit hid.
{31369}{31489}I don't remember askin' you|a goddamned thing !
{31588}{31648}You were sayin' ?
{31651}{31711}It's in the cupboard.
{31807}{31897}N-No, the one|by your kn-knees.
{32525}{32585}We happy ?
{32588}{32678}Vincent ?
{32682}{32742}- We happy ?|- Yeah, we happy.
{32807}{32927} Look, I'm sorry, uh, l--|I didn't get your name.
{32932}{33052}I got yours. Vincent. Right ?|B-But I never got yours.
{33057}{33207}- My name's Pitt, and your ass|ain't talkin' your way outta this shit.
{33245}{33335}I just want you|to know how--
{33401}{33520}I just want you to know how sorry we are|th-that things got so fucked up...
{33525}{33585}with us and Mr. Wallace.
{33588}{33708}W-We got into this thing with|the best intentions. Really. I never--
{33713}{33833}Oh, I'm sorry,|did I break your concentration ?
{33838}{33898}- I didn't mean to do that. Please.
{33901}{34051}Continue. You were saying something|about "best intentions."
{34120}{34210}What's the matter ?|Oh, you were finished !
{34214}{34304}Oh, well, allow me to retort.
{34433}{34492}What does Marsellus Wallace|look like ?
{34494}{34584}What ?
{34588}{34678}- What country you from ?|- What ?
{34682}{34802}- "What" ain't no country I ever|heard of. They speak English in What ?
{34807}{34897}- English, motherfucker !|Do you speak it ?
{34901}{34931}- Then you know what I'm sayin' !|- Yes.
{34932}{35052}Describe what Marsellus Wallace|looks like !
{35057}{35117}- What ? l--|- Say "what" again !
{35120}{35240}Say "what" again ! I dare ya !|I double dare you, motherfucker !
{35245}{35365}- Say "what" one more goddamn time !|- H-H-He's black.
{35370}{35430}- Go on !|- He's bald !
{35433}{35522}- Does he look like a bitch ?|- What ?
{35557}{35677}Does he look... Iike a bitch ?
{35682}{35802}- No !|- Then why you tryin'
{35807}{35897}- I didn't.|- Yes, you did. Yes, you did, Brett !
{35901}{35961}- You tried to fuck him.|- No, no.
{35963}{36113}But Marsellus Wallace don't like to be|fucked by anybody except Mrs. Wallace.
{36120}{36210}- You read the Bible, Brett ?|- Yes !
{36214}{36364}Well, there's this passage|I got memorized. Sort of
{36370}{36430}Ezekiel 25:17.
{36433}{36523}"The path of the righteous man...
{36526}{36645}is beset on all sides|by the inequities of the selfish...
{36651}{36741}and the tyranny of evil men.
{36744}{36894}Blessed is he who,|in the name of charity and goodwill,
{36901}{36991}shepherds the weak|through the valley of darkness,
{36995}{37085}for he is truly|his brother's keeper...
{37089}{37179}and the finder|of lost children.
{37182}{37302}And I will strike down upon thee|with great vengeance...
{37308}{37368}and furious anger...
{37370}{37490}those who attempt to poison|and destroy My brothers !
{37495}{37614}And you will know|My name is the Lord...
{37619}{37709}when I lay My vengeance|upon thee !"
{38276}{38336}I think you gonna find...
{38339}{38429}when all this shit|is over and done--
{38495}{38615}I think you're gonna find yourself|one smilin' motherfucker.
{38651}{38741}The thing is, Butch,
{38744}{38834}right now...|you got ability.
{38901}{38961}But painful as it may be,
{38963}{39053}ability... don't last.
{39120}{39240}And your days are just about over.
{39245}{39365}Now, that's a hard|motherfuckin' fact of life.
{39370}{39520}But that's a fact of life your ass|is gonna have to get realistic about.
{39589}{39738}You see, this business is filled to|the brim with unrealistic motherfuckers.
{39744}{39864}Motherfuckers who thought|their ass would age like wine.
{39932}{40022}If you mean it turns|to vinegar... it does.
{40057}{40177}If you mean it gets better|with age... it don't.
{40245}{40305}Besides, Butch,
{40370}{40460}how many fights you think|you got in you anyway ?
{40464}{40524}Hmm ?
{40527}{40587}Two ?
{40620}{40739}Boxers don't have|an old-timers' day.
{40776}{40866}You came close,|but you never made it.
{40901}{41021}And if you were gonna make it,|you would have made it before now.
{41527}{41587}You my nigger ?
{41714}{41803}Certainly appears so.
{41995}{42085}The night of the fight,|you may feel a slight sting.
{42182}{42302}That's pride fuckin' with you.
{42339}{42399}Fuck pride !
{42464}{42554}Pride only hurts.
{42558}{42618}It never helps.
{42652}{42712}You fight through that shit.
{42746}{42895}'Cause a year from now,|when you kickin' it in the Caribbean,
{42901}{43051}you gonna say to yourself,|"Marsellus Wallace was right."
{43120}{43240}I got no problem|with that, Mr. Wallace.
{43245}{43365}In the fifth,|your ass goes down.
{43495}{43525}Say it.
{43620}{43710}In the fifth,|my ass goes down.
{43777}{43836}Yo, Vincent Vega.|Our man in Amsterdam.
{43838}{43988}Jules Winfield, our man in lnglewood.|Get your asses on in here.
{43995}{44085}- Goddamn, nigger,|what's up with them clothes ?
{44089}{44179}Where's the big man ?
{44214}{44274}The big man's right over there|takin' care of some business.
{44276}{44426}Why don't you hang back a second or two.|You see the white boy leave, go on over.
{44495}{44585}How ya been ?
{44589}{44679}- I been doin' pretty good.|How 'bout yourself ?
{44746}{44836}So I hear you're|takin' Mia out tomorrow.
{44932}{44992}At Marsellus's request.
{45026}{45086}- Have you met Mia ?|- Not yet.
{45089}{45209}- What's so fuckin' funny ?
{45214}{45274}- Not a goddamn thing.|- I got to piss.
{45276}{45396}Look, I'm not a fuckin' idiot,|all right ? It's the big man's wife.
{45401}{45491}I'm gonna sit across from her,|chew my food with my mouth closed,
{45495}{45555}Iaugh at her fuckin' jokes,|and that's it.
{45558}{45648}Hey, my name's Paul,|and this shit's between y'all.
{45652}{45742}Then what'd you fuckin'|ask me about it for ?
{45746}{45806}Asshole.
{45995}{46085}- Gimme a pack of Red Apples.|- Filters ?
{46089}{46119}No.
{46214}{46334}- You lookin' at somethin', friend ?|- You ain't my friend, palooka.
{46401}{46491}-What was that ?|-I think you heard me just fine, punchy.
{46495}{46585}Vincent Vega's in the house ?
{46589}{46679}My nigger,|get your ass over here.
{46902}{46991}- What's up ?|- Man, I'm really sorry.
{46995}{47055}You shouldn't worry about it.
{47057}{47147}Pack of Red Apples. $1.40.
{47214}{47304}And some matches.
{47401}{47461}Thanks.
{47495}{47615} It's as if it turns every part|of your body into the tip of a penis.
{47652}{47742}- Whoa.|- I'll lend it to you.
{47746}{47896}That gun to pierce your ears,|they don't use that to pierce
{47902}{47992}Forget that gun. That guns goes against|the entire idea behind piercing.
{47996}{48145}All my piercing, 18 places on my body,|every one of 'em done with a needle.
{48151}{48241}Five in each ear, one through|the nipple of my left breast,
{48276}{48366}two in my right nostril,|one in my left eyebrow,
{48370}{48430}one in my belly,|one in my lip, one in my clit,
{48433}{48553}- and I wear a stud in my tongue.|- Excuse me.
{48558}{48618}I was just curious,
{48620}{48710}but, um... why would you wear|a stud in your tongue ?
{48746}{48836}Sex thing.|Helps fellatio.
{48839}{48959}Vincenzo.|Step in my office.
{49151}{49241}This is Panda from Mexico.|Very good stuff.
{49245}{49365}Now, that's Bava.|Different, but equally good.
{49370}{49430}And that is Choco|from the Harz Mountains of Germany.
{49464}{49584}Now, the first two are the same.|300 a gram. Those are friend prices.
{49589}{49679}But this one|is a little more expensive.
{49683}{49743}This is 500 a gram.
{49746}{49836}But, when you shoot it, you will know|where that extra money went.
{49839}{49959}There's nothing wrong with these two.|This is real, real, real good shit.
{49965}{50084}But this one|is a fuckin' madman.
{50089}{50179}Remember, I just got back|from Amsterdam.
{50182}{50272}Am I a nigger ?|Are we in lnglewood ? No.
{50276}{50366}You're in my home. Now, white people|who know the difference...
{50370}{50460}between good shit and bad shit,|this is the house they come to.
{50464}{50554}Now, my shit, I'll take the Pepsi|Challenge with that Amsterdam shit...
{50558}{50648}- any old day of the fuckin' week.|- That's a bold statement.
{50652}{50772}This ain't Amsterdam, Vince.|This is a seller's market.
{50777}{50897}Coke is fuckin' dead|as... dead.
{50902}{51022}Heroin, it's comin' back|in a big fuckin' way.
{51058}{51147}- All right.|Gimme three grams of madman.
{51151}{51271}Now, if it's as good as you say it is,|I'll come back and buy another thousand.
{51276}{51336}I just hope that I still|have some left for ya,
{51339}{51459}but I'm givin' you some|out of my own private stash.
{51464}{51584}That is what a nice guy I am.
{51589}{51679}- I'm outta balloons.|Is a baggie all right ?
{51714}{51744}All right.|I'll just get one for ya.
{51777}{51897}Honey, will you get me some baggies|and, uh, twistix from the kitchen ?
{51902}{51962}Okay.
{51965}{52085}Hey, uh, what do you think about Trudi ?|She ain't got a boyfriend.
{52090}{52179}- You wanna hang out and get high ?|- Which one's Trudi ?
{52182}{52302}-The one with all the shit in her face ?|-No, that's Jody.
{52308}{52368}That's my wife.
{52370}{52520}- I'm sorry, man.|- Thank you.
{52527}{52647}- No, I can't. I gotta be someplace.|- All right, no problemo.
{52652}{52712}- I'll take a rain check.
{52714}{52834}- Oh.|- Thank you, Jody.
{52839}{52929}Still got your Malibu ?
{52933}{53023}Oh, man, you know what some fucker|did the other day ?
{53027}{53087}- What ?|- Fuckin' keyed it.
{53090}{53180}- Oh, man, that's fucked up.|- Tell me about it.
{53184}{53273}I had it in storage|for three years.
{53276}{53396}It was out five days, and some|dickless piece of shit fucked with it.
{53401}{53551}They should be fuckin' killed,|man. No trial, no jury,
{53558}{53678}I wish I could've caught him|doin' it. I'd have given
{53683}{53833}- It'd been worth him doin' it|just so I could've caught him.
{53839}{53899}What's more chicken-shit|than fuckin' with a man's automobile ?
{53933}{53993}- Don't fuck with another man's vehicle.|- You don't do it.
{53996}{54086}- It's just against the rules.|- Thank you.
{54090}{54150}Thank you.
{54152}{54242}- Mind if I shoot up here ?|- Hey, mi casa es su casa.
{54246}{54335}Muchas gracias.
{57433}{57523} Hi, Vincent.|I'm getting dressed. The door's open.
{57558}{57678}Come inside and make yourself|a drink. Mia.
{57933}{57993}Hello ?
{57996}{58116} Billy Raye was a preacher's son|and when his daddy would visit
{58121}{58181}Vincent.
{58277}{58337}Vincent.
{58340}{58400}I'm on the intercom.
{58403}{58462}Where is--|Where is the intercom ?
{58464}{58584}It's on the wall|by the two African fellows.
{58589}{58649}To your right.
{58746}{58806}Warm.
{58808}{58868}Warmer.
{58871}{58931}Disco.
{58933}{58993}Hello ?
{58996}{59116}Push the button|if you want to talk.
{59121}{59181}Hello ?
{59184}{59274}Go make yourself a drink, and I'll|be down in two shakes of a lamb's tail.
{59277}{59397}The bar's by the fireplace.
{59464}{59524}Okay.
{59527}{59587} When he started|sweet talkin' to me
{59589}{59679} He come and tell me|everything is all right
{59683}{59743} He'd kiss me and tell me|everything is all right
{59746}{59806} Can I get away|again tonight
{59808}{59898} The only one who could|ever reach me
{59902}{59962} Was the son|of a preacher man
{59965}{60055} The only boy|who could ever teach me
{60058}{60148} Was the son of a preacher man|Yes, he was
{60152}{60242} He was
{60246}{60306}- Lord he knows he was|- Yes he was
{60403}{60463} How will I remember
{60465}{60554} The look was in his eyes
{60558}{60618} Stealing kisses from me|on the sly
{60621}{60711} Taking time to make time
{60714}{60774} Telling me that|he's all mine
{60777}{60867}- Learning from each other's knowin'
{60871}{60931} Looking to see|how much we've grown
{60933}{61023} And the only one|who could ever reach me
{61027}{61087} Was the son|of a preacher man
{61090}{61180} The only boy|who could ever teach me
{61184}{61244} Was the son of a preacher man|Yes, he was
{61246}{61336}- Was, was|- He was
{61340}{61400}- Oh, yes he was
{61434}{61464}Let's go.
{61652}{61712}What the fuck is this place ?
{61714}{61804}This is Jackrabbit Slim's.
{61808}{61868}- An Elvis man should love it.
{61871}{61991}- Come on, Mia. Let's go get a steak.|- You can get a steak here, daddy-o.
{61996}{62086}Don't be a--
{62090}{62180}Oh, after you, kitty-cat.
{62777}{62897}Good evening, ladies and gentlemen.|Now, how may I help you ?
{62902}{62992}- There's a reservation under Wallace.|- Wallace ?
{62996}{63056}- We reserved a car.
{63058}{63238}Oh, a car. Why don't you seat 'em|over there in the Chrysler.
{63246}{63336} School get out, baby|Gonna tell you some news
{63340}{63400} Sure do look good|in them baby doll shoes
{63403}{63553} One, two, buckle the shoes|Three, four, get out on the floor
{63559}{63708} Five, six, come get your kicks down at|the corner of Lincoln and 46th, yeah
{63808}{63868} All right
{63965}{64025} I've been waitin' in school|all day long
{64027}{64087} Waiting on the bell to ring|so I can go home
{64090}{64150} Throw my books on the table|Pick up the telephone
{64184}{64244}- Come on, baby|- Coffee, please ? Decaf.
{64246}{64306}- Just a minute.|- Heading down to the drugstore
{64309}{64369} Throw a nickel in the jukebox|Then we start to rock
{64371}{64431} School's out, baby|Gonna tell you some news
{64434}{64494} You sure do look good|in them baby doll shoes
{64496}{64586} Well, it's one, two|Buckle the shoes
{64590}{64650} Three, four|Get out on the floor
{64653}{64772} Five, six, come get your kicks|down at the corner of Lincoln and 46th
{64933}{65023} Gonna rock all night|Just wait and see
{65027}{65117}Ricky, Ricky, Ricky !
{65184}{65274}Let's hear it for Ricky Nelson !
{65277}{65367}- Fantastic job, Rick.|Thank you very much.
{65496}{65586} Just to let you|all know, Ricky will be back
{65590}{65709}so we hope you enjoy your meals|here at Jackrabbit Slim's.
{65746}{65806}Thank you.
{65808}{65898}Call for...
{65902}{66052}- Phil-lip Mor-ris.|- What do you think ?
{66059}{66179}I think it's like|a wax museum with a pulse.
{66184}{66304}Hi, I'm Buddy.|What can I get you ?
{66371}{66521}Let's see, steak, steak, steak. Oh,|yeah, I'll have the Douglas Sirk steak.
{66528}{66588}- I'll have that.|- How do you want that cooked ?
{66590}{66710}- Burned to a crisp or bloody as hell ?|- Bloody as hell, and--
{66715}{66774}Oh, yeah, look at this--|vanilla Coke.
{66777}{66837}What about you, Peggy Sue ?
{66840}{66930}I'll have the...
{66965}{67085}Durward Kirby burger, bloody.
{67090}{67180}And... a five-dollar shake.
{67215}{67275}How do you want that shake,|Martin and Lewis, or Amos 'n Andy ?
{67278}{67398}- Martin and Lewis.|- Did you just order
{67403}{67463}Mm-hmm.
{67465}{67555}That's a shake ?|That's milk and ice cream ?
{67559}{67709}- Last I heard.|- That's five dollars ? You don't
{67715}{67775}- No.|- Just checking.
{67778}{67867}I'll be right back|with your drinks.
{67871}{67931} To Lonesome Town
{67933}{68023} To cry my troubles away
{68090}{68210}Could you, um...|roll me one of those, cowboy ?
{68215}{68305}You can have this one, cowgirl.
{68309}{68369}- Thanks.
{68371}{68431} The streets are filled|with regret
{68496}{68556}Think nothin' of it.
{68559}{68679} Lay me down|in Lonesome Town
{68684}{68774}- I can learn to forget|- So...
{68778}{68867}Marsellus said|you just got back from Amsterdam.
{68871}{68961}- Sure did.|- How long were you there ?
{68965}{69055}Just over three years.
{69121}{69211}I go there about once a year|to chill out for a month.
{69215}{69335}No kiddin' ?|I didn't know that.
{69340}{69430}Why would you ?
{69559}{69619}I heard you did a pilot.
{69653}{69773}- That was my 15 minutes.|- What was it ?
{69778}{69897}It was a show about a team of female|secret agents called Fox Force Five.
{69902}{69992}- What ?|- Fox Force Five.
{69996}{70056}Fox, as in were a bunch|of foxy chicks.
{70059}{70149}Force, as in we're a force|to be reckoned with.
{70152}{70212}And five, as in there's|one-two-three-four-five of us.
{70215}{70335}There was a blond one,|Sommerset O'Neal. She was the leader.
{70340}{70430}The Japanese fox|was a kung fu master.
{70434}{70554}The black girl|was a demolition expert.
{70559}{70649}French fox's speciality was sex.
{70653}{70773}- What was your speciality ?|- Knives.
{70778}{70838}The character I played,|Raven McCoy,
{70841}{70960}her background was she grew up|raised by circus performers.
{70965}{71085}According to the show,|she was the deadliest woman
{71090}{71180}And she knew|a zillion old jokes.
{71184}{71304}Her grandfather,|an old vaudevillian, taught her.
{71309}{71399}And if we would have got picked up,|they would've worked in a gimmick...
{71403}{71523}where every show|I would've told another joke.
{71559}{71649}You know any of them old jokes ?
{71653}{71743}Well, I only got the chance to say one|'cause we only did one show.
{71747}{71837}- Tell me.|- It's corny.
{71872}{71932}Don't be that way.|Tell me.
{71934}{72023}- No, you wouldn't like it,|and I'd be embarrassed.
{72027}{72147}You told 50 million people,|and you can't tell me ?
{72152}{72272}- I promise I won't laugh.|- That's what I'm afraid of, Vince.
{72278}{72338}That's not what I meant.|You know it.
{72340}{72460}Now I'm definitely not gonna tell you|'cause it's been built up too much.
{72465}{72525}What a gyp.
{72559}{72619}Martin and Lewis.
{72716}{72806}Vanilla Coke.
{72934}{73023}Mmm. Yummy.
{73027}{73117}You think I could|have a sip of that ?
{73152}{73242}Be my guest.
{73246}{73336}I gotta know what|a five-dollar shake tastes like.
{73371}{73461}- You can use my straw.|I don't have cooties.
{73465}{73555}Cooties I can handle.
{73559}{73619}All right.
{73809}{73899}Goddamn, that's a pretty|fuckin' good milkshake !
{73903}{74023}-Told ya.|-I don't know if it was worth $5,
{75090}{75180}- Don't you hate that ?|- Hate what ?
{75184}{75244}Uncomfortable silences.
{75309}{75459}Why do we feel it's necessary|to yak about bullshit
{75465}{75555}I don't know.|That's a good question.
{75559}{75709}That's when you know|you found somebody really special.
{75716}{75866}When you can just shut the fuck up for|a minute and comfortably share silence.
{75872}{75992}Well, I don't think we're quite|there yet, but don't feel bad.
{76028}{76118}I'll tell you what.
{76122}{76211}I'm gonna go to the bathroom|and powder my nose.
{76215}{76305}You sit here...|and think of something to say.
{76371}{76401}I'll do that.
{76497}{76527}Okay.
{77309}{77369}I said goddamn !
{77371}{77461}Goddamn !|Goddamn.
{77528}{77618}I need some hair spray.
{77809}{77839}Mmmm.
{77872}{77992}Don't you just love it when you|come back from the bathroom to
{77997}{78057}We're lucky|we got anything at all.
{78060}{78150}I don't think Buddy Holly's|much of a waiter.
{78154}{78243}Maybe we should've sat|in Marilyn Monroe's section.
{78246}{78336}- Which one ? There's two Monroes.|- No, there's not.
{78340}{78400}That is Marilyn Monroe.
{78434}{78494}That is Mamie Van Doren.
{78497}{78647}I don't see Jayne Mansfield,|so she must have the night off.
{78653}{78743}- Pretty smart.|- Yeah. I got my moments.
{78747}{78897}- So did you think of somethin' to say ?|- Actually, I did.
{78935}{78995}However...
{79060}{79150}you seem like|a really nice person, and l--
{79154}{79214}- I don't want to offend you.|- Oooh.
{79216}{79365}This doesn't sound like|the usual, mindless, boring,
{79371}{79461}This sounds like you|actually have somethin' to say.
{79465}{79555}Well, well, I do. I do.
{79559}{79679}- But you have|to promise not to be offended.
{79684}{79804}You can't promise somethin' like that.|I have no idea what you're gonna ask me.
{79809}{79959}You can ask me what you're gonna|ask me, and my natural response
{79966}{80026}Then, through no fault of my own,|I would have broken my promise.
{80028}{80118}- Let's just forget it.|- That's an impossibility.
{80122}{80242}Trying to forget anything|as intriguing as this would be
{80247}{80306}- Is that a fact ?|- And besides,
{80309}{80459}- isn't it more, uh, exciting|when you don't have permission ?
{80465}{80555}Well, here goes.
{80559}{80649}What did you think about|what happened to Antwan ?
{80653}{80743}- Who's Antwan ?|- Tony Rocky Horror. You know him.
{80747}{80837}- He fell out of a window.|- Hmm. Hmm.
{80841}{80991}Well, that is one way to say it.|Another way to say it would be
{80997}{81087}Another way would be|he was thrown out by Marsellus.
{81091}{81241}Yet even another way is to say|he was thrown out of a window
{81247}{81307}- Is that a fact ?|- No.
{81310}{81399}No, it's not a fact. It's just what|I heard. That's just what I heard.
{81403}{81493}- Who told you ?|- They.
{81497}{81587}"They" talk a lot, don't they ?
{81653}{81713}They certainly do.|They certainly do.
{81716}{81866}- Don't be shy, Vincent.|What else did "they" say ?
{81872}{81932}- Um--|- Did it involve the "F" word ?
{81935}{82055}No, no, no, no, no.|They just said that Antwan
{82091}{82181}- And ?|- And-- And nothin'.
{82185}{82275}That's it.
{82279}{82339}You heard Marsellus...
{82341}{82460}threw Tony Rocky Horror|out of a fourth-story window
{82465}{82525}- Mm-hmm.|- And you believe that ?
{82528}{82648} Well, at the time|I was told it sounded reasonable.
{82684}{82774}Marsellus throwing Tony out|of a fourth-story window...
{82778}{82868}for massaging my feet|seemed reasonable ?
{82872}{82962}No, it seemed excessive,|but that doesn't mean it didn't happen.
{82966}{83056}I understand that Marsellus|is very protective of you.
{83060}{83180}A husband being protective|of his wife is one thing.
{83185}{83305}A husband almost killing|another man for touching
{83310}{83370}But did it happen ?
{83373}{83552}Only thing Antwan ever touched|of mine was my hand when he
{83559}{83619}Really ?
{83622}{83742}Truth is, nobody knows why Marsellus|threw Tony out that window...
{83747}{83777}except Marsellus and Tony.
{83809}{83899}When you little scamps get together,|you're worse than a sewing circle.
{83935}{84025}Ladies and gentlemen. Now the moment|you've all been waiting for.
{84028}{84178}The world-famous|Jackrabbit Slim's twist contest.
{84247}{84397}Now, this is where|one lucky couple...
{84404}{84523}will win this handsome trophy|that Marilyn here is holding.
{84528}{84618}Now, who will be|our first contestants ?
{84622}{84712}- Right here !|- All right !
{84716}{84806}- I wanna dance.|- No, no, no, no, no.
{84809}{84929}No, no, no, no, no. I do believe|Marsellus, my husband, your boss,
{84935}{85055}told you to take me out|and do whatever I wanted.
{85060}{85150}Now I wanna dance;|I wanna win; I want that trophy.
{85154}{85184}- So dance good.|- All right. You asked for it.
{85185}{85245}- So dance good.|- All right. You asked for it.
{85247}{85337}Let's hear it|for our first contestants.
{85466}{85615}Now let's meet our first|contestants here this evening.
{85622}{85682}Mrs. Mia Wallace.
{85684}{85774}And how 'bout your fella here ?
{85778}{85808}Vincent Vega.
{85841}{85931}All right, let's see what you can do.|Take it away !
{85935}{86025}- Go for it.|- Come on !
{86559}{86679} It was a teenage wedding|and the old folks wished them well
{86747}{86867} You could see that Pierre|did truly love the mademoiselle
{86935}{87055} And now the young monsieur|and madame have rung the chapel bell
{87122}{87242} C'est la vie say the old folks|It goes to show you never can tell
{87310}{87430} They furnished off an apartment|with a two-room Roebucks sale
{87466}{87585} The 'coolerador was crammed|with TV dinners and ginger ale
{87653}{87773} But when Pierre found work|the little money comin'
{87841}{87961} C'est la vie say the old folks|It goes to show you never can tell
{88028}{88148} They had a hi-fi phono|and boy did they let it blast
{88216}{88336} Seven hundred little records|all rock, rhythm and jazz
{88404}{88524} But when the sun went down|the rapid tempo of the music fell
{88560}{88709} C'est la vie say the old folks|It goes to show you never can tell
{89498}{89618} They had a teenage wedding|and the old folks wished them well
{89684}{89774} You could see that Pierre|did truly love the mademoiselle
{90841}{90931}Is that what you call|an uncomfortable silence ?
{90935}{91055}I don't know|what you call that.
{91060}{91120}- Drinks ! Music !
{91154}{91214}I'm gonna take a piss.
{91216}{91366}That's a little bit more information|than I needed, but go right ahead.
{91778}{91838} Girl
{91841}{91871} Bomp, bomp, bom
{91872}{91992} You'll be a woman soon
{92091}{92151} I love you so much|Can't count all the ways
{92154}{92244} I'd die for you, girl|and all they can say is
{92247}{92337} He's not your kind
{92341}{92491} You never get tired of putting me down|and I never know when I come around
{92498}{92588} What I'm gonna find
{92592}{92712} Don't let them|make up your mind
{92717}{92806} Don't you know, girl
{92841}{92931} You'll be a woman soon
{92935}{93025}One drink, and that's it.
{93028}{93148}Don't be rude.|Drink your drink, but do it quickly.
{93216}{93276}Say good night...|and go home.
{93341}{93461} You'll be a woman soon
{93498}{93558} Soon
{93623}{93713} You'll be a woman
{93748}{93837} I've been misunderstood|for all of my life
{93841}{93901} But what they're sayin', girl|it cuts like a knife
{93903}{93993} The boy's no good
{93997}{94057} Well, I've finally have found|what I been lookin' for
{94060}{94210} But if they get a chance|they'll end it for sure
{94216}{94276} Baby, I've done|all I could
{94279}{94429} You see, this is|a moral test of oneself.
{94435}{94525}Whether or not|you can maintain loyalty.
{94529}{94619}Because... being loyal|is very important.
{94623}{94773} You never get tired of putting me down|and I never know when I come around
{94779}{94839} What I'm gonna find
{94842}{94961} Don't let them|make up your mind
{94966}{95056} Don't you know, girl
{95091}{95211} You'll be a woman soon
{95279}{95339} Please
{95373}{95463} Come take my hand
{95529}{95589} Girl
{95623}{95743} You'll be a woman soon
{95779}{95839} Please
{95873}{95962} Come take my hand
{96029}{96059}- Hello.|- Girl
{96122}{96242}So, you're gonna go out there|and you're gonna say, "Good night.
{96248}{96308}I've had a very lovely evening."
{96310}{96460}Walk out the door, get in|the car, go home, jerk off,
{96623}{96713} Now it's up to you, girl
{96748}{96868} You'll be a woman soon
{96936}{96995}- Please
{96997}{97087} Come take my hand
{97154}{97274}- Girl
{97279}{97369}- You'll be a woman soon
{97435}{97495} Soon
{97529}{97619} You'll be a woman
{97904}{97964}All right, Mia.
{97967}{98056}So listen, I gotta go,|all right ?
{98154}{98244}Oh, Jesus fucking Christ.
{98279}{98339}You fu--|Oh, Jesus Christ !
{98341}{98401}Oh, fuck me.|Fuck me !
{98404}{98554}Oh-- Come on, girl. We're gettin'|outta here. We gotta walk now.
{98842}{98932}Don't fuckin' die on me, Mia !
{98936}{98996}Fuck !
{99216}{99276}Answer.
{99279}{99339}Have you got the ring ?
{99341}{99461}- Why, certainly.|- Join hands, you two lovebirds.
{99467}{99557}- Please ! Please !
{99560}{99620}Yes, yes.|Hold hands, you lovebirds.
{99811}{99871}Fuck you, Lance !|Answer !
{100030}{100089}Now what do you say ?
{100091}{100181} I give up !|I'll marry you !
{100185}{100305}- Lance !|The goddamn phone's ringing !
{100373}{100433}I can hear it.
{100435}{100525}I thought you told those|fuckin' assholes never to
{100529}{100589}Yeah, I told them.
{100592}{100682}And that is exactly what I'm going|to tell this fucking asshole right now.
{100748}{100838}Don't you dare strike me !|- Hello.
{100842}{100902}Lance ! Vincent.
{100904}{100994}I'm in big fuckin' trouble, man.|I'm coming to your house.
{100998}{101118}W-Whoa. Whoa. Hold your horses, man.|W-What's the problem ?
{101123}{101212}- I got this chick,|she's fuckin' O.D.in' on me !
{101216}{101336}I'm not even joking with you !|Do not be bringing some
{101341}{101401}- No choice.|- Wh-- She's O.D.in' ?
{101404}{101494}- She's fuckin' dyin' on me, man !|- Just dandy.
{101498}{101618}Okay, then you bite|the fuckin' bullet, take her
{101623}{101713}- Negative !|- This is not my fuckin' problem, man !
{101717}{101807}You fucked her up,|you fuckin' deal with this !
{101811}{101901}Uh, are you talkin' to me|on a cellular phone ?
{101904}{101994}I don't know you.|Who is this ? Don't come here !
{101998}{102088}I'm hanging up the phone !|Prank caller ! Prank caller !
{102341}{102401}- What the hell was that ?
{102467}{102557}Have you lost|your fucking mind ?
{102560}{102650}- You were talking about drug|shit on a cellular phone !
{102654}{102714}- You crashed your car|into my fucking house !
{102717}{102837}Are you deaf ? You are not bringing|this fucked-up bitch into my house !
{102842}{102932}This "fucked-up bitch"|is Marsellus Wallace's wife.
{102936}{102996}- Do you know who Marsellus Wallace is ?|- Yeah.
{102998}{103088}If she croaks on me,|I am a fucking grease spot !
{103092}{103211}I will be forced to tell him|that you did not help and
{103216}{103306}Now, come on. Help me, help me.|Pick her up.
{103341}{103401}- Shit.
{103467}{103527}Lance !
{103529}{103589}Shit.
{103592}{103682}It's 1:30 in the goddamn morning.
{103686}{103776}What the fuck's going on out here ?
{103779}{103839}Who's she ?
{103842}{103932}Go to the fridge and get the thing|with the adrenalin shot.
{103936}{103996}- What's wrong with her ?|- She's O.D.ing !
{103998}{104058}- Get her outta here !|- Get the shot !
{104061}{104151}- Fuck you ! Fuck you too !|- What a fuckin' bitch.
{104155}{104215}Just keep talking to her,|all right ?
{104217}{104306}She's gettin' the shot. I'm going|to go get my little black medical book.
{104310}{104370}What the fuck you need|a medical book for ?
{104373}{104433}I've never had to give|an adrenalin shot before !
{104435}{104525}I don't go joy-poppin'|with bubble-gummers !
{104529}{104619}- Get the shot !|- I am, if you'll let me !
{104623}{104713}- I ain't stopping you !|- Stop talking to me.
{104717}{104777}- Get the shot !|- All right !
{104873}{104963}Hurry up. We're losing her !|- I'm looking as fast as I can !
{104967}{105027}What's he looking for ?
{105030}{105120}I don't know. Some book.|- What are you looking for ?
{105123}{105213}- A little black medical book.|- What are you looking for ?
{105217}{105336}My little black medical book ! It's|like a textbook they give to nurses.
{105341}{105401}- I never saw no medical book.|- Trust me. I have one.
{105435}{105495}- If it's so important,|why don't you keep it with the shot ?
{105498}{105618}- Stop bothering me !|- While you're looking, that girl's
{105623}{105683}You're never gonna find|anything in this mess !
{105686}{105806}- I'm gonna fucking kill you|if you don't shut up !
{105811}{105931}- Right ? Pig.|- Get the fuck outta my way.
{105936}{106026}- Quit fuckin' around|and give her the shot.
{106061}{106151}you take off her shirt|and find her heart.
{106155}{106245}- Does it gotta be exact ?|- We're giving her a shot in the heart,
{106249}{106338}I don't know exactly where her heart is.|I think it's right here.
{106341}{106461}- That's it.|- All right, what I need is
{106467}{106527}- You got it ?|- What ?
{106529}{106589}A magic marker.|A felt pen !
{106592}{106682}A fuckin' black magic marker !|Christ.
{106686}{106836}- Come on, man. Hurry up !|- Fuck ! Okay, okay.
{106936}{106996}- Hurry up, man.|- I'll tell you what to do.
{106998}{107088}- You're gonna give her the shot.|- No, you're gonna give her the shot.
{107092}{107182}- I ain't giving her the shot.|I never done this before.
{107186}{107276}I ain't starting now !|You brought her here.
{107280}{107370}The day I bring an O.D.ing bitch|to your house, then I give her the shot.
{107374}{107433}Give it to me.|Give me that.
{107435}{107525}All right, tell me what to do.
{107529}{107619}Okay, you're giving her an injection|of adrenalin straight to her heart.
{107623}{107713}- But she's got a breastplate--|You gotta pierce through that.
{107717}{107807}You gotta bring the needle|down in a stabbing motion.
{107811}{107901}- I gotta-- I gotta|stab her three times ?
{107905}{107995}But it's gotta be hard enough to get|through her breastplate into her heart.
{108030}{108090}Once you do that,|you p-press down on the p-plunger.
{108092}{108182}- Okay. Then what happens ?|- Kinda curious about that myself.
{108186}{108276}This ain't no fuckin' joke !|Am I gonna kill her ?
{108280}{108370}- She's supposed to come out|of it like that. It's--
{108374}{108433}- All right. Ready ?|- One.
{108592}{108652}Two.
{108873}{108933}Three !
{109374}{109463}If you're all right,|then say something.
{109467}{109557}Something.
{109560}{109620}That was fuckin' trippy.
{109717}{109807}- Ohh.|- Oh, man.
{110560}{110590}Mia. Mia.
{110686}{110746}What's--
{110748}{110838}What's your thoughts on-- on--
{110842}{110902}on how to handle this ?
{110905}{110965}What's yours ?
{111061}{111151}Well, I'm of the opinion|that if Marsellus lived his whole life,
{111155}{111275}he doesn't need to know|nothing about this incident.
{111280}{111370}If Marsellus knew|about this incident,
{111374}{111434}I'd be in as much trouble as you.
{111436}{111496}I seriously doubt that.
{111530}{111589}I can keep a secret if you can.
{111654}{111714}Shake on it ?
{111873}{111933}Mum's the word ?
{111936}{111996}Cool.
{111998}{112148}Now, if you'll excuse me, I'm going|to go home and have a heart attack.
{112217}{112277}Vincent.
{112343}{112433}Do you wanna hear|my Fox Force Five joke ?
{112468}{112528}Sure.
{112530}{112619}Except I think I'm still|a little too petrified to laugh.
{112623}{112683}No, you won't laugh|'cause it's not funny.
{112686}{112806}But if you still wanna hear it,|I'll tell it.
{112811}{112871}- I can't wait.|- Okay.
{112873}{112963}Three tomatoes|are walkin' down the street.
{112967}{113027}Papa Tomato, Mama Tomato|and Baby Tomato.
{113030}{113150}Baby Tomato starts lagging behind,|and Papa Tomato gets really angry.
{113155}{113245}Goes back and squishes him|and says,
{113249}{113309}"Ketchup."
{113405}{113465}Ketchup.
{113593}{113652}See you around.
{114280}{114370}Oh, that Paddlefoot.|He funny, silly dog.
{114405}{114465}He think totem pole alive !
{114468}{114558}He arctic tenderfoot !
{114562}{114681}That totem pole been here forever !
{114686}{114746}- Butch ?
{114748}{114808}One more thing, and we'll start for--
{114811}{114901}- Butch, stop watching TV for a second.|- Yeah ?
{114905}{115025}- You've got a special visitor.|- Stand up. Stand up.
{115092}{115242}Now, do you remember when I told you|your daddy died in a P.O.W. camp ?
{115249}{115369}Well, this here is Captain Koons.
{115374}{115464}He was in the P.O.W. camp|with Daddy.
{115624}{115684}Hello, little man.
{115687}{115806}Boy, I sure heard|a bunch about you.
{115811}{115901}See, I was a good friend|of your dad's.
{115905}{115995}We were in that Hanoi|pit of hell together...
{115998}{116058}over five years.
{116061}{116121}Hopefully...
{116124}{116214}you'll never have to|experience this yourself,
{116217}{116307}but when two men are in a situation|like me and your dad were...
{116311}{116401}for as long as we were,
{116405}{116525}you take on certain responsibilities|of the other.
{116530}{116590}If it'd been me who'd--
{116655}{116685}not made it,
{116687}{116836}Major Coolidge'd be talking right now|to my son Jim.
{116842}{116932}But the way it turned out,|I'm talking to you.
{116967}{117027}Butch...
{117092}{117152}I got something for ya.
{117343}{117403}This watch I got here...
{117405}{117555}was first purchased|by your great-grandfather
{117562}{117682}It was bought in a little general store|in Knoxville, Tennessee.
{117687}{117806}Made by the first company|to ever make wristwatches.
{117811}{117871}Up 'til then, people just|carried pocket watches.
{117905}{117995}It was bought|by Private Doughboy Erine Coolidge...
{117998}{118058}on the day he set sail for Paris.
{118061}{118151}This was your|great-grandfather's war watch,
{118155}{118245}and he wore it every day|he was in that war, and...
{118249}{118369}when he'd done his duty,|he went home to your great-grandmother,
{118374}{118494}took the watch off,|put it in an old coffee can,
{118499}{118619}until your granddad, Dane Coolidge,|was called upon by his country...
{118624}{118744}to go overseas and fight|the Germans once again.
{118749}{118838}This time they called it|World War ll.
{118842}{118992}Your great-grandfather gave this watch|to your granddad for good luck.
{118998}{119088}Unfortunately, Dane's luck|wasn't as good as his old man's.
{119092}{119182}Dane was a Marine,|and he was killed...
{119186}{119306}along with all the other Marines|at the battle of Wake lsland.
{119311}{119401}Your granddad was facing death.
{119405}{119465}He knew it.
{119468}{119588}None of those boys ever|had any illusions about
{119593}{119683}so three days before the Japanese|took the island,
{119687}{119837}your granddad asked|a gunner on an Air Force transport,
{119843}{119932}a man he'd never met before|in his life--
{119936}{120026}to deliver to his infant son,
{120030}{120150}who he'd never seen in the flesh,|his gold watch.
{120155}{120275}Three days later, your granddad|was dead, but Winocki kept his word.
{120280}{120400}After the war was over,|he paid a visit to your grandmother,
{120405}{120555}delivering to your infant father|his dad's gold watch.
{120562}{120592}This watch.
{120781}{120930}This watch was on your daddy's wrist|when he was shot down over Hanoi.
{120936}{121056}He was captured,|put in a Vietnamese prison camp.
{121061}{121181}He knew if the gooks|ever saw the watch,
{121186}{121276}it'd be confiscated,|taken away.
{121280}{121400}The way your dad looked at it,|this watch was your birthright.
{121405}{121525}He'd be damned if any slope's|gonna put their greasy, yellow
{121530}{121620}so he hid it in one place he knew|he could hide something-- his ass.
{121624}{121744}Five long years|he wore this watch up his ass.
{121749}{121869}Then he died of dysentery--|He give me the watch.
{121874}{121993}I hid this uncomfortable|hunk of metal up my ass two years.
{121998}{122058}Then...
{122061}{122181}after seven years,|I was sent home to my family and...
{122186}{122216}now...
{122311}{122401}Iittle man,|I give the watch to you.
{123092}{123122}It's time, Butch.
{123374}{123464}ln the heavyweight division,
{123468}{123558}- in the right corner|wearing the blue trunks,
{123562}{123652}weighing 210 pounds,
{123655}{123745}Floyd Ray Wilson !
{123843}{123903}It's official. It's official.
{123906}{123996}- Wilson is dead !|- Well, Dan,
{124000}{124059}hands down, the most brutal fight|this city's ever seen.
{124061}{124181}Coolidge was out of there|faster than I've ever seen
{124186}{124246}- Do you think he knew Wilson was dead ?|- My guess would be yes.
{124280}{124370}I could see the frenzy in his|eyes give way to the realization
{124374}{124464}- I think any man would've|left the ring that fast.
{124468}{124528}is gonna affect|the world of boxing ?
{124530}{124650}A tragedy like this can't help|but shake the world of boxing
{124655}{124775}It's of paramount importance,|during the sad weeks ahead,
{125812}{125872}Man, you know I didn't--
{125906}{125966}- Marsellus.|- No, it wasn't. I didn't do it.
{125968}{126028}I didn't do it.
{126031}{126121}- How you doing ?|- Great.
{126125}{126184}I never thanked you|for dinner.
{126249}{126309}- What you got ?|- He booked.
{126311}{126401}- His trainer ?|- Says he don't know nothin'.
{126405}{126495}- I think Butch surprised|his ass same as us.
{126499}{126619}We wanna know. Take him to|the kennel, sic the dogs on his ass.
{126624}{126714}We'll find out for goddamn sure|what he knows and what he don't.
{126718}{126778}Butch's search--|How do you want it done ?
{126781}{126871}I'm prepared to scour the Earth|for that motherfucker.
{126874}{126964}If Butch goes to lndochina, I want|a nigger hiding in a bowl of rice...
{126968}{127028}ready to pop a cap in his ass.
{127031}{127091}I will take care of it.
{127405}{127465}Mister.
{127562}{127622}- Hey, mister.|- What ?
{127624}{127774}You were in that fight,|the fight on the radio.
{127781}{127871}- You're the fighter ?|- Whatever gave you that idea ?
{127874}{127964}No, come on.
{127968}{128028}You're him.
{128031}{128091}I know you're him.
{128156}{128215}Tell me you're him.
{128218}{128278}I'm him.
{128311}{128371}You killed the other boxing man.
{128499}{128559}He's dead ?
{128562}{128622}The radio said he was dead.
{128718}{128778}Sorry about that, Floyd.
{128812}{128872}What does it feel like ?
{128906}{128936}What does what feel like ?
{128937}{128997}Killing a man.
{129062}{129182}Beating another man to death|with your bare hands.
{129187}{129247}What are you, a weirdo ?
{129250}{129309}No.
{129311}{129401}It is a subject|I have much interest in.
{129468}{129558}You are the first person|I have ever met who has killed somebody.
{129655}{129715}So ?
{129718}{129808}- What does it feel like to kill a man ?
{129843}{129903}I'll tell you what.
{129906}{130026}Give me one of them cigarettes|you got up there, and I'll
{130562}{130652}So, Esmarelda...
{130687}{130807}Villa Lobos--|Is that Mexican ?
{130812}{130902}The name is Spanish,|but I am Colombian.
{130906}{130996}- That's some handle|you got there, honey.
{131000}{131060}And what is your name ?
{131062}{131122}Butch.
{131125}{131185}Butch.
{131187}{131336}- What does it mean ?|- I'm an American, honey.
{131343}{131403}So, moving right along,
{131405}{131465}Esmarelda,
{131468}{131558}what is it you want to know ?
{131562}{131682}- I want to know what it|feels like to kill a man.
{131874}{131994}Didn't know he was dead|'til you told me he was dead.
{132000}{132150}Now that I know he's dead,|you wanna know how I feel about it ?
{132250}{132370}I don't feel|the least bit bad about it.
{132687}{132747}What the fuck'd I tell ya ?|Huh ?
{132749}{132869}As soon as the word got out|the fix was in, man, the odds
{132874}{132934}I know. I know.|Unbelievable.
{132937}{133057}Hey, fuck him, Scotty. If he was|a better boxer, he'd still be alive.
{133062}{133122}If he never|laced up his gloves,
{133125}{133185}which he never shoulda done in the first|fuckin' place, he'd still be alive.
{133250}{133370}Yeah, well, who gives a fuck ?|It's over now.
{133375}{133434}Yeah, well, enough about the poor,|unfortunate Mr. Floyd.
{133437}{133557}Let's talk about the rich|and prosperous Mr. Butch.
{133562}{133652}How many bookies did you|lay it around on ?
{133656}{133716}All eight ?|How long to collect ?
{133781}{133871}So you'll have it all|by tomorrow night ? No, I understand.
{133875}{133965}A few stragglers aside.|Oh, fuck, Scotty, that is good news.
{133968}{134028}That is great news, man.
{134031}{134151}Yeah. Mm-hmm. No, me and Fabienne|are gonna leave in the morning.
{134156}{134246}It'll probably take us|a couple days to get down to Knoxville.
{134250}{134310}Okay, my brother.
{134312}{134372}You're right.
{134375}{134435}You're goddamn right.
{134468}{134558}All right, Scotty, next time I see you,|it'll be on Tennessee time.
{134562}{134622}Cool, brother.
{135093}{135153}$45.60.
{135250}{135310}And, uh,
{135312}{135432}here's a little something|for the effort.
{135438}{135527}Now, if anybody asks you who your fare|was tonight, what are you gonna say ?
{135530}{135590}The truth.
{135593}{135713}Three well-dressed,|slightly toasted Mexicans.
{135781}{135841}Bonsoir,|Esmarelda Villa Lobos.
{135843}{135903}Buenas Noches, Butch.
{136250}{136310}Whew.
{136344}{136404}Keep the light off.
{136406}{136496}- Is that better, Sugar Pop ?|- Oui.
{136624}{136684}Hard day at the office ?
{136687}{136747}Pretty hard.
{136749}{136809}Got in a fight.
{136812}{136872}Poor baby.
{136875}{136965}Can you make spoons ?
{136968}{137058}You know what ?|I was thinkin' about takin' a shower.
{137062}{137182}- I'm stinkin' like a dog over here.|- I like the way you stink.
{137187}{137247}Let me take this jacket off.
{137312}{137432}- I was looking at myself in the mirror.|- Uh-huh.
{137438}{137468}I wish I had a pot.
{137531}{137650}You were looking|at yourself in the mirror,
{137656}{137746}A pot.|A pot belly.
{137749}{137809}Pot bellies are sexy.
{137812}{137872}Well, you should be happy,
{137875}{137935}'cause you have one.
{137937}{138057}Shut up, fatso.|I don't have a pot.
{138062}{138152}I have a bit of a tummy,|like Madonna when she did "Lucky Star."
{138156}{138216}It's not the same thing.
{138219}{138339}I didn't know there was|such a difference between
{138344}{138404}The difference is huge.
{138406}{138496}Would you like it if I had a pot belly ?
{138500}{138560}No.
{138563}{138712}Pot bellies make a man|look either oafish or like a gorilla.
{138718}{138808}But on a woman|a pot belly's very sexy.
{138812}{138962}The rest of you is normal-- normal face,|normal legs, normal hips, normal ass--
{138968}{139088}but with a big,|perfectly round pot belly.
{139094}{139184}If I had one, I'd wear a T-shirt|two sizes too small...
{139187}{139247}to accentuate it.
{139250}{139310}You think men|would find that attractive ?
{139312}{139402}I don't give a damn|what men find attractive.
{139406}{139526}It's unfortunate what we find pleasing|to the touch and pleasing to the eye...
{139531}{139561}is seldom the same.
{139687}{139777}If you had a pot belly,|I would punch you in it.
{139781}{139871}- You'd punch me in the belly ?|- Right in the belly.
{139875}{139935}Ohh ! I'd smother you !
{139937}{140057}- I'd drop it right on your face|'til you couldn't breathe !
{140062}{140122}- You'd do that ?|- Yeah.
{140125}{140185}- Promise ?|- Yeah.
{140281}{140341}- Mmm.|- Mmm.
{140406}{140466}Oh.
{140594}{140654}Did you get everything ?
{140657}{140716}- Yes, I did.|- Good job, Sugar Pop.
{140749}{140779}Did everything|go as planned ?
{140781}{140871}- You didn't listen to the-- Ow !
{140875}{140935}You didn't listen to the radio ?
{140937}{141027}I never listen to your fights.|Were you the winner ?
{141031}{141121}I won, all right.
{141125}{141185}- Are you still retiring ?|- Sure am.
{141219}{141279}So it all worked out|in the finish.
{141313}{141403}We're not at the finish yet, baby.
{141657}{141747}We're in a lot of danger,|aren't we ?
{141781}{141871}If they find us,|they'll kill us, won't they ?
{141937}{142027}But they won't find us,|will they ?
{142125}{142215}Do you still want me|to go with you ?
{142250}{142370}I don't want to be a burden|or a nuisance. It's--
{142563}{142623}Say it.
{142625}{142715}- Fabienne,
{142719}{142808}I want you to be with me.
{142812}{142902}- Forever ?|- Forever and ever.
{142968}{143028}Do you love me ?
{143031}{143091}Very, very much.
{143250}{143340}- Butch.|- Yes ?
{143375}{143435}Will you give me|oral pleasure ?
{143500}{143560}Will you kiss it ?
{143625}{143685}But you first.
{143688}{143778}- Okay.|- Okay.
{144062}{144152}Butch.
{144156}{144246}Mon amour.|L'aventure commence.
{144719}{144779}I think I cracked a rib.
{144782}{144901}- Giving me oral pleasure ?|- No, retard, from the fight.
{144906}{144996}- Don't call me "retard."|- My name is Fabby.
{145000}{145060}- My name is Fabienne !|- Stop it.
{145062}{145122}- Stop it !|- My name is Fabi--
{145125}{145215}Shut up, fuckhead !|I hate that mongoloid voice.
{145219}{145309}Okay, okay.|Sorry, sorry, sorry.
{145313}{145403}- I take it back.
{145469}{145559}Will you hand me a dry towel,|Miss Beautiful Tulip ?
{145563}{145683}- Oh, I like that.|I like being called a tulip.
{145688}{145748}"Tulip" is much better|than "mongoloid."
{145751}{145841}I didn't call you a mongoloid.|I called you a retard.
{145844}{145904}And I took it back.
{145907}{145966}- Butch ?
{145968}{146028}Yes, Lemon Pie ?
{146031}{146121}- Where are we going to go ?|- Well, I'm not sure yet.
{146156}{146216}Wherever you want.
{146219}{146279}We're gonna get a lot|of money from this,
{146313}{146373}but it ain't gonna be|the kind of money...
{146375}{146465}that we can live like hogs|in the fathouse forever.
{146469}{146589}I was thinking maybe we could go|down someplace in the South Pacific.
{146594}{146684}Kind of money we're gonna have's gonna|carry us a long way down there.
{146688}{146778}- If we wanted,|we could live in Bora Bora ?
{146782}{146902}And if after a while you didn't|dig that, we could go someplace else.
{146907}{146966}Maybe Tahiti, Mexico.
{146968}{146998}But I do not speak Spanish.
{147031}{147091}Well, you do not speak|Bora-Boran either.
{147094}{147154}Besides, Mexican's easy.
{147156}{147246}- ¿ Donde esta el zapateria ?|- What does that mean ?
{147250}{147310}Where is the shoe store?
{147313}{147373}- ¿ Donde esta--|- Spit, please.
{147438}{147528}- ¿ Donde esta el zapateria ?|- Excellent pronunciation.
{147532}{147592}- Mmm.
{147594}{147684}You'll be my little mamacita|in no time.
{147719}{147779}- ¿ Que hora es ?|- ¿ Que hora es ?
{147782}{147842}- What time is it ?|- What time is it ?
{147844}{147934}Time for bed.
{147938}{147998}Sweet dreams, jellybean.
{148219}{148279}Butch ?
{148438}{148498}Never mind.
{148719}{148809}Aah !
{148813}{148933}Merde ! You startled me.|Did you have a bad dream ?
{149250}{149370}- What is this you're watching ?|- A motorcycle movie.
{149375}{149435}I'm not sure the name.
{149469}{149559}- Are you watching it ?|- In a way.
{149625}{149745}It's a little early in the morning|for explosions and war.
{149844}{149964}- What was it about ?|- How should I know ?
{149970}{150089}- No, imbecile,|what was your dream about ?
{150094}{150154}I don't remember.
{150156}{150246}It's really rare|that I remember my dreams.
{150250}{150340}Well, let's look|at the grumpy man in the morning.
{150406}{150466} Why don't you get up|and we'll get some breakfast.
{150469}{150559}One more kiss,|and I'll get up.
{150625}{150715}- Satisfied ?|- Yep.
{150719}{150839}- Get up, lazy bones !|- Ohh !
{150844}{150934}- Ohh. God.
{150970}{151060}- What time is it ?|- Almost nine in the morning.
{151063}{151182}- What time does our train arrive ?|- Eleven.
{151187}{151307}- You know what I'm gonna|have for breakfast ?
{151313}{151433}I'm gonna order a big plate|of blueberry pancakes...
{151438}{151498}with maple syrup,
{151500}{151590}eggs over easy|and five sausages.
{151594}{151684}Anything to drink with that ?
{151688}{151778}Wow, that looks nice.
{151782}{151872}To drink-- A tall glass|of orange juice...
{151876}{151966}and a black cup of coffee.
{151970}{152090}- After that, I'm going to|have a slice of pie.
{152095}{152214}- Any time of the day|is a good time for pie.
{152219}{152309}Blueberry pie|to go with the pancakes.
{152313}{152403}And on top, a thin slice|of melted cheese.
{152406}{152466}Where's my watch ?
{152594}{152654}It's there.
{152657}{152747}- No, it's not.|- Have you looked ?
{152751}{152871}Yes, I've fuckin' looked.|What the fuck do you think I'm doin' ?
{152876}{152936}You sure you got it ?
{152938}{152998}Yes.|Bedside table drawer.
{153001}{153121}- On the little kangaroo ?|- Yes, it was on the little kangaroo.
{153126}{153215}Yeah, well,|it's not here now.
{153219}{153279}- Well, it should be.
{153313}{153403}Yes, it most definitely should be,|but it's not here now !
{153563}{153683}Fabienne,|where's my father's fucking watch ?
{153719}{153869}Do you have any idea what he had|to go through to get me that watch ?
{153876}{153966}I don't have time to go into it,|but he went through a lot.
{153970}{154120}All this other shit you could've set|on fire, but I specifically reminded
{154126}{154156}Now think.
{154157}{154276}- Did you get it ?|- I believe so.
{154281}{154371}"You believe so" ?|What the fuck does that mean ?
{154406}{154466}Then I did.
{154500}{154560}Are you sure ?
{154594}{154654}No.
{154719}{154779}Fuck ! Fuck ! Fuck !
{154782}{154842}Motherfucker !|Motherfuckin'--
{154907}{154997}Do you know how fucking stupid|you fucking are ?
{155001}{155061}No !
{155126}{155186}It's not your fault.
{155344}{155404}You left it at the apartment.
{155563}{155683}If you left it at the apartment,|it's not your fault.
{155751}{155841}I had you bring|a bunch of stuff.
{155907}{155967}I reminded you about it,
{155970}{156090}but I didn't illustrate|how personal the watch was to me.
{156095}{156215}If all I gave a fuck about was|the watch, I shoulda told you that.
{156220}{156310}You're not a mind reader.
{156314}{156343}Are you ?
{156657}{156717}I-- I'm sorry.
{156719}{156839}Don't be. Just means|I can't have breakfast with you.
{156844}{156904}Why does it mean that ?
{157001}{157091}Because I gotta go back to my apartment|and get my watch.
{157126}{157186}Won't the gangsters|be looking for you there ?
{157220}{157340}Well, that's what|I'm gonna find out.
{157345}{157434}If they are, and I don't think|I can handle it,
{157438}{157498}then I'll split.
{157500}{157620}I saw your watch. I thought|I brought it. I'm so sorry.
{157782}{157872}Here's some money.|Go out and get those pancakes.
{157876}{157936}Have a nice breakfast.
{157938}{158028}I'll take your Honda. I'll be back|before you can say "blueberry pie."
{158032}{158122}Blueberry pie.
{158126}{158186}Maybe not that fast.
{158189}{158279}- But pretty fast. Okay ?|- Okay.
{158282}{158342}- Bye.|- Bye.
{158345}{158434}Shit ! Of all the fuckin' things|she could fuckin' forget,
{158438}{158498}she forgets my father's watch !
{158500}{158560}I specifically reminded her--
{158563}{158623}bedside table, on the kangaroo.
{158625}{158715}I said the words:|"Don't forget my father's watch."
{159189}{159279}Visit the Jackrabbit Slim's|nearest you...
{159594}{159714}i EI burro !
{163439}{163469}Lookin' good, Butch.
{168564}{168624} lf I were walkin'|in your shoes
{168845}{168995} Countin' flowers on the wall|That don't bother me at all
{169001}{169121} Playin' solitaire 'til dawn|with a deck of fifty-one
{169126}{169216}That's how you're gonna|beat 'em, Butch.
{169220}{169310}- Smokin' cigarettes and|watchin' Captain Kangaroo
{169314}{169374} Now don't tell me
{169439}{169529} Countin' flowers on the wall
{169533}{169653} That don't bother me at all
{169658}{169808} Playin' solitaire 'til dawn|with a deck of fifty-one
{169814}{169963} Smokin' cigarettes|and watchin' Captain Kangaroo
{169970}{170030} Now don't tell me
{170032}{170122} I've nothin' to do
{170126}{170186} It's good to see you|I must go
{170189}{170249} I know I look a fright
{170251}{170341}- Anyway my eyes|- Motherfucker.
{170345}{170405}- Are not accustomed--|- Uhh !
{170658}{170718}- Do you think he's dead ?|- He's dead.
{170720}{170780}- Oh, my God.|- He's dead.
{171095}{171185}If you need someone to go|to court, I'll be glad to help.
{171220}{171280}He hit you, then he|crashed into that car.
{171283}{171343}- Who ?|- Him.
{171470}{171530}I'll be damned.
{171877}{171937}- Ohh !
{172001}{172091}- Aaaah ! I'm shot !
{172283}{172373}- Sally ! Sally !
{172502}{172562}- Aaah !
{172627}{172687}Motherfucker !
{172752}{172842}- Can I help you with somethin' ?|- Shut the fuck up.
{172877}{172937}Now you just wait|a goddamn minute, now !
{172939}{172999}What the fuck you up to ?
{173002}{173091}- Come here, motherfucker !
{173095}{173185}- You feel that sting, huh, big boy ?
{173189}{173249}That's pride|fuckin' with you, see ?
{173251}{173341}You gotta fight through that shit !| Huh ?
{173345}{173435}- You'd better kill me--|- Yeah, somebody's gonna get killed.
{173439}{173499}Somebody's gonna get|their motherfuckin' head blown to--
{173533}{173593}- Hold it right there, goddamn it.
{173595}{173715}- This ain't none|of your business, mister.
{173720}{173780}- Toss the weapon.|- You don't understand, man.
{173783}{173843}Toss the weapon.
{173908}{173998} It's time
{174002}{174091}- To find love|- Take your foot off the nigger,
{174095}{174155}- put your hand behind your head,
{174157}{174217}approach the counter right now.
{174220}{174280}- This motherfucker's trying to...
{174283}{174313}kill me.
{174314}{174434}Shut up.|Keep comin'. Come on.
{174502}{174592} lf love
{174595}{174655} ls shelter
{175189}{175219}Zed. Maynard.
{175283}{175343}Yeah, the spider|just caught a couple flies.
{175376}{175466} Whoa, my angel
{175533}{175623} Down to you
{175627}{175627} Down to you
{176783}{176873}Nobody kills anybody|in my place of business...
{176877}{176967}- except me or Zed.
{177033}{177093}That's Zed.
{177470}{177560}- I thought|you said you waited for me.
{177721}{177781}Then how come they're all beat up ?
{177783}{177933}They did that to each other, man.|They came in fightin'.
{177940}{178060}Now, this 'un right here,|he was gonna shoot that one.
{178065}{178155}Is that right ?|You gonna shoot him, boy ?
{178158}{178247}Huh ?
{178314}{178374}Hey, is Grace|all right out front ?
{178408}{178498}- Yeah. It ain't Tuesday, is it ?|- No, it's Thursday.
{178502}{178562}- She oughta be fine.|- Mmm.
{178627}{178747}Well, bring out the Gimp.
{178783}{178843}I think the Gimp's sleepin'.
{178846}{178966}Then I guess you'll just have to go|wake him up now, won't you ?
{180159}{180219}Get up.
{180595}{180655}Get down.
{180971}{181061}Which one of 'em|you wanna do first ?
{181065}{181155}- I ain't for sure yet.
{181284}{181343}Eenie-meenie-minie-mo,
{181345}{181435}catch a nigger...
{181439}{181499}by his toe.
{181502}{181622}If he hollers, let him go.
{181627}{181747}Eenie-meenie-minie-mo.
{181846}{181936}My mother said...
{181940}{182030}pick the perfect one,
{182033}{182123}and... you... are...
{182190}{182220}it.
{182315}{182404}- Guess that means you, big boy.|- Fuck you !
{182408}{182468}- Shh.
{182533}{182653}- You wanna do it in here ?|- No, let's take him back
{182658}{182748}Sounds good to me.
{183470}{183560}You keep an eye on this 'un.
{184346}{184465}Yeah !
{184533}{184653}Now ! Go ! Come on, motherfucker !
{184658}{184748}- Now, motherfucker !|Aaah !
{184752}{184872}- Come on ! Yeah !
{185065}{185155}- Yeah !
{185378}{185438}- Ohh !|- Yeah !
{185503}{185592}- Yeah ! Yeah !
{185658}{185718}Yeee !|Yeeee-hah !
{186346}{186406}Yeah !
{187252}{187342}Come on !|Get down there !
{187440}{187530}Aaah !|Do it ! Yeah !
{188033}{188123}Yeah ! Yeah !
{188597}{188686}- Shut the fuck up !
{188752}{188812}Fuck him !
{188877}{188937}Come on !
{189033}{189153}- Fuck him. Yeah.
{189440}{189530}Aaaaah !
{189659}{189718}- Aaaaah !
{190065}{190125}You want that gun,|don't ya, Zed ?
{190190}{190250}Huh ?
{190284}{190314}Go ahead and pick it up.
{190409}{190469}Go ahead. Pick it up.
{190534}{190624}Come on--|Thatta boy !
{190659}{190778}I want you to pick it up, Zed.
{190908}{190998}- Step aside, Butch.
{191378}{191468}Fuck !
{191534}{191624}- You okay ?
{191659}{191719}No, man.
{191722}{191811}I'm pretty fuckin' far from okay.
{192159}{192249}- What now ?
{192315}{192375}"What now" ?
{192409}{192499}- Let me tell you what now.
{192534}{192594}I'm gonna call a couple of hard,|pipe-hittin' niggers...
{192597}{192687}to go to work|on the homes here...
{192690}{192780}with a pair of pliers|and a blowtorch.
{192846}{192936}You hear me talkin',|hillbilly boy ?
{192971}{193031}I ain't through with you|by a damn sight !
{193033}{193123}I'm gonna get medieval|on your ass.
{193221}{193311}I meant what now|between me and you.
{193471}{193531}Oh, that "what now."
{193597}{193687}- I tell you what now|between me and you.
{193753}{193842}There is no me and you.
{193877}{193937}Not no more.
{194033}{194093}So, are we cool ?
{194127}{194187}Yeah, we cool.
{194190}{194250}- Two things.
{194315}{194405}Don't tell nobody about this.
{194440}{194560}This shit is between me, you...
{194565}{194685}and Mr. "Soon-To-Be-Livin'|The-Rest-Of-His-Short-Ass-
{194690}{194750}rapist here.
{194784}{194874}It ain't nobody else's business.
{194878}{194937}Two:
{194940}{195030}You leave town tonight.|Right now.
{195096}{195126}And when you gone,
{195127}{195187}you stay gone,
{195190}{195280}- or you be gone.
{195284}{195374}You lost all your L.A. privileges.|Deal ?
{195440}{195500}Deal.
{195534}{195594}Get your ass outta here.
{196378}{196438}Oh, shit.
{197440}{197500}Fabienne !
{197534}{197624}Fabienne !
{197659}{197719}Fabienne !|Come on, baby.
{197722}{197842}- Come on. Get your shit.|We gotta go right now.
{197847}{197937}- What about our bags ?|- Fuck the bags; if we don't split
{197941}{198001}- I'll be downstairs.|- Is everything well ?
{198003}{198122}- Just come on ! No talking now !|- Are we in danger ?
{198221}{198281}Come on, honey !
{198346}{198406}Where did you get|this motorcycle ?
{198409}{198559}- It's not a motorcycle, baby.|It's a chopper. Let's go.
{198565}{198655}I'm sorry, baby,|I had to crash that Honda.
{198659}{198749}Come on. Let's go,|let's go, let's go.
{198878}{198968}- You're hurt ?|- No, no, I might've broken
{199003}{199062}Come on. Hop on.|Baby, please, we--
{199065}{199155}Honey, we gotta hit|the fuckin' road ! Get on !
{199221}{199311}- Oh, baby, I'm sorry.|Come here, come here.
{199315}{199375}I'm sorry. Mmm.
{199378}{199498}- I'm so sorry.|- You were gone so long, I started
{199503}{199593}I didn't mean to worry you.|Everything's fine.
{199597}{199657}- How was your breakfast ?|- It was good.
{199659}{199719}Did you get|the blueberry pancakes ?
{199722}{199812}They didn't have blueberry; I had to get|buttermilk. Are you sure you're okay ?
{199816}{199906}Since I left you,|this has been, without a doubt,
{199909}{199999}the single weirdest|fuckin' day of my life--
{200035}{200065}Gotta go. Come on.
{200066}{200155}Butch, whose motorcycle|is this ?
{200159}{200249}- It's a chopper, baby.|- Whose chopper is this ?
{200253}{200313}- Zed's.|- Who's Zed ?
{200315}{200375}Zed's dead, baby.|Zed's dead.
{200878}{200938}Yes, you did, Brett !
{200941}{201031}You tried to fuck him,|and Marsellus Wallace
{201035}{201125}by anybody except Mrs. Wallace.
{201128}{201217}- Oh, God, please. I don't wanna die.|- You read the Bible, Brett ?
{201221}{201311}- Yes !|- Well, there's this passage
{201315}{201375}Sorta fits the occasion.
{201378}{201468}Ezekiel 25:17.
{201471}{201621}"The path of the righteous man|is beset on all sides...
{201628}{201688}by the inequities|of the selfish...
{201690}{201780}- and the tyranny of evil men.
{201784}{201904}Blessed is he who, in the name|of charity and good will,
{201909}{201999}shepherds the weak|through the valley of darkness,
{202003}{202093}for he is truly|his brother's keeper...
{202097}{202186}and the finder|of lost children.
{202190}{202310}And I will strike down upon thee|with great vengeance...
{202315}{202375}and furious anger...
{202378}{202498}those who attempt to poison|and destroy My brothers.
{202503}{202623}And you will know|My name is the Lord...
{202628}{202718}when I lay My vengeance|upon thee."
{202972}{203032}I'm fucked.|Oh, fuck. Oh, fuck.
{203035}{203125}- ls he a friend of yours ?|- Oh, goddamn. Goddamn.
{203128}{203217} Hmm ? Oh.|Vincent, Marvin. Marvin, Vincent.
{203221}{203311}- Better tell him to shut up.|He's gettin' on my nerves.
{203315}{203405}Marvin. Marvin !|I'd knock that shit off if I was you.
{203409}{203529}- Die, you motherfuckers ! Die !
{204378}{204468}Why the fuck didn't you tell us|somebody was in the bathroom ?
{204503}{204563}Slip your mind ? Did you forget|that someone was in there...
{204565}{204625}with a goddamn hand cannon ?
{204628}{204748}You see the size of that gun he fired|at us ? It was bigger than him.
{204909}{204969}We should be fuckin' dead, man.
{204972}{205032}I know.|We was lucky.
{205035}{205125}No, no, no, no.|That shit wasn't luck.
{205128}{205248}- Yeah, maybe.|- This was divine intervention.
{205254}{205313}You know what|divine intervention is ?
{205503}{205563}I think so.
{205565}{205655}That means that God came down|from Heaven and stopped the bullets.
{205659}{205719}That's right.|That's exactly what it means.
{205753}{205813}God came down from Heaven|and stopped these motherfuckin' bullets.
{205878}{205938}I think it's time for us|to leave, Jules.
{205941}{206001}Don't do that.|Don't fuckin' blow this shit off !
{206003}{206123}- What just happened here|was a fuckin' miracle !
{206128}{206188}Wrong ! Wrong.|This shit doesn't "just happen."
{206222}{206312}Do you want to continue|this theological discussion in a car...
{206316}{206375}or in a jailhouse|with the cops ?
{206378}{206468}We should be fuckin' dead,|my friend !
{206472}{206592}What happened here was a miracle, and I|want you to fucking acknowledge it !
{206597}{206747}All right, it was a miracle.|Can we go now ?
{206941}{207031}Let's go, nigger !|Come on ! Shit.
{207097}{207157}You ever seen that show Cops ?
{207160}{207250}I was watching it one time,|and there was this cop on,
{207254}{207374}and he was talkin' about this|gunfight he had in the hallway
{207379}{207468}He just unloaded on this guy and nothin'|happened. He didn't hit nothin'.
{207472}{207562}Okay ? It was just|him and this guy.
{207565}{207655}I mean, you know, it's,|it's freaky, but it happens.
{207659}{207809}You wanna play blind man,|go walk with the shepherd,
{207816}{207906}- What the fuck does that mean ?|- It means that's it for me.
{207910}{208000}From here on in, you can|consider my ass retired.
{208003}{208063}- Jesus Christ. Goddamn it.|- Don't blaspheme.
{208066}{208156}- I said, don't do that !|- Hey, why are you fuckin'
{208160}{208250}Look, I'm tellin' Marsellus today--|I'm through.
{208254}{208344}- Why don't you tell him|at the same time why ?
{208347}{208466}- And I bet you $10,000|he laughs his ass off.
{208472}{208562}Marvin, what do you make of all this ?
{208565}{208625}Man, I don't even|have an opinion.
{208628}{208748}You gotta have an opinion. You think|God came down from Heaven and stopped--
{208753}{208813}- What the fuck's happenin' ?
{208816}{208876}- Aw, shit, man !|- Aw, man !
{208878}{208968}- Oh, man, I shot Marvin in the face.|- Why the fuck'd you do that ?
{208972}{209032}I didn't mean it.|It was an accident.
{209035}{209125}- Man, I seen some crazy-ass|shit in my time, but this--
{209128}{209218}It was an accident. We probably|went over a bump or somethin'.
{209222}{209252}The car ain't hit|no motherfuckin' bump.
{209285}{209375}I didn't mean to shoot|the son of a bitch. The gun went off.
{209379}{209468}Look at this fuckin' mess ! We're on|a city street in broad daylight here !
{209472}{209562}- I don't believe it !|- Well, believe it now, motherfucker !
{209565}{209655}We gotta get this car off|the road. Cops notice shit
{209659}{209749}- Just take it to|a friendly place, that's all !
{209753}{209843}Marsellus ain't got|no friendly places in the Valley.
{209847}{209937}- Well, Jules, this ain't|my fuckin' town, man !
{209941}{210001}- What you doing ?|- I'm calling my partner in Toluca Lake.
{210003}{210123}-Where's Toluca Lake ?|-Over the hill here, by Burbank Studios.
{210129}{210219}If Jimmie's ass ain't home,|I don't know what the fuck we gonna do,
{210222}{210312}'cause I ain't got|no other partners in 818.
{210316}{210376}Jimmie, how you doin', man ?|It's Jules. Just listen up, man.
{210410}{210500}Me and my homeboy are in a car, and we|gotta get it off the road, pronto.
{210504}{210593}I need to use your garage|for a couple hours.
{210628}{210718}We gotta be real fuckin' delicate|with this Jimmie situation.
{210722}{210812}He's one remark away|from kickin' our asses out the door.
{210816}{210906}- If he does, what do we do ?|- We ain't leavin'
{210910}{211000}but I don't want it to reach|that pitch-- Jimmie's a friend.
{211003}{211093}You don't come into your friend's house|and start tellin' him what's what.
{211097}{211157}Just tell him|not to be abusive.
{211160}{211220}He kinda freaked out back there|when he saw Marvin.
{211222}{211312}Put yourself in his position--|It's 8:00 in the morning,
{211316}{211376}He wasn't expectin' this shit.
{211379}{211469}We gotta remember here|who's doin' who a favor.
{211473}{211592}If that favor means I gotta|take shit, he can stick that
{211597}{211687}- Fuck, nigger, what the fuck'd|you just do to his towel, man ?
{211691}{211781}- You're supposed to wash 'em first !|- You watched me wash 'em.
{211784}{211904}- I watched you get 'em wet.|- I was washin' 'em.
{211910}{211970}Maybe if he'd had Lava|I coulda done a better job.
{211972}{212032}I used the same|fuckin' soap you did,
{212035}{212095}and when I finished, the towel|didn't look like no goddamn maxi-pad !
{212129}{212189}What if he was to come in here|and see his towel like this ?
{212191}{212311}It's shit like this that's gonna bring|this situation to a head, man !
{212316}{212436}Look, I ain't threatenin' you|or nothin', all right ?
{212441}{212561}You know I respect you and all.|But just don't put me
{212566}{212655}All right.|Fine. Fine.
{212659}{212749}Ask me nice like that,|no problem.
{212753}{212813}Just go handle your friend.|Go ahead. I don't care.
{212878}{212968}Mmm ! Goddamn, Jimmie !
{212972}{213032}This some serious|gourmet shit.
{213035}{213095}Me and Vincent|would've been satisfied...
{213097}{213157}with some freeze-dried|Taster's Choice.
{213160}{213220}Right ?
{213222}{213312}And he springs this|serious gourmet shit on us.
{213316}{213376}- What flavor is this ?|- Knock it off, Julie.
{213379}{213499}- What ?|- I don't need you to tell me
{213504}{213564}I'm the one who buys it.|I know how good it is.
{213566}{213626}When Bonnie goes shopping,|she buys shit.
{213629}{213748}I buy the gourmet expensive stuff 'cause|when I drink it, I wanna taste it.
{213753}{213843}But you know what's on|my mind right now ? It ain't
{213847}{213937}It's the dead nigger|in my garage.
{213941}{214031}- Jimmie, don't even worry--|- Don't tell me about anything.
{214035}{214095}When you came pulling in here,
{214097}{214187}did you notice the sign|on the front of my house that said,
{214191}{214281}- You know I ain't seen no--|- Did you notice the sign on
{214285}{214345}that said,|"Dead Nigger Storage" ?
{214348}{214438}No. I didn't.
{214441}{214531}- You know why you didn't|see that sign ?
{214535}{214655}'Cause it ain't there,|'cause storing dead niggers
{214660}{214749}- We're not gonna store|the motherfucker--
{214753}{214873}that if Bonnie comes home and|finds a dead body in her house,
{214910}{215000}No marriage counselor.|No trial separation.
{215003}{215093}Okay ? And I don't wanna|get fuckin' divorced !
{215097}{215247}Man, you know, fuck, I wanna help you,|but I don't wanna lose my wife doin' it.
{215254}{215314}Jimmie, Jimmie,|she ain't gonna leave you.
{215316}{215436}Don't fuckin' "Jimmie" me, Jules !|Okay ? Don't fuckin' "Jimmie" me.
{215441}{215561}There's nothin' you're gonna|say that's gonna make me forget
{215660}{215779}Now, look, you know, she comes home|from work in about an hour and a half.
{215784}{215874}The graveyard shift|at the hospital.
{215878}{215968}You gotta make some phone calls ?|You gotta call some people ?
{215972}{216092}Well, then, do it, and then get the fuck|out of my house before she gets here.
{216097}{216187}That's Kool and the Gang.|We don't wanna fuck your shit up.
{216191}{216281}All I wanna do is call my people|and get 'em to bring us in.
{216285}{216375}You're fucking my shit up|right now !
{216379}{216469}You're gonna fuck my shit up|big time if Bonnie comes home.
{216473}{216563}Do me that favor, all right ?|The phone is in my bedroom.
{216567}{216657}Well, say she comes home.
{216660}{216720}What do you think she'll do ?
{216784}{216844}Oh, no fuckin' shit she'll freak.
{216847}{216907}That ain't no kinda answer.
{216910}{217000}I mean, you know, I don't.|How much ? A lot or a little ?
{217003}{217093}You got to appreciate|what an explosive element...
{217097}{217157}this Bonnie situation is.
{217160}{217280}She comes home from a hard day's work,|finds a bunch of gangsters
{217285}{217345}doing a bunch of gangster shit,
{217348}{217438}there ain't no tellin'|what she's liable to do.
{217504}{217564}Yeah, I grasp that, Jules.
{217567}{217627}All I'm doing is|contemplating the ifs.
{217629}{217719}I don't wanna hear about|no motherfuckin' ifs !
{217723}{217842}All I want to hear from your ass|is, "You ain't got no problem,
{217847}{217967}Chill them niggers out|and wait for the cavalry,
{217972}{218062}You ain't got no problem, Jules.
{218066}{218126}I'm on the motherfucker.
{218129}{218279}Chill them niggers out and wait for|the Wolf, who should be coming directly.
{218285}{218375}You sendin' the Wolf ?
{218379}{218439}Oh, you feel better,|motherfucker ?
{218441}{218501}Shit, yeah, negro !
{218504}{218594}That's all you had to say !
{218598}{218688}- She the hysterical type ?
{218692}{218782}- When is she due ?
{218786}{218845}Mm-hmm.
{218847}{218907}Give me|the principals' names again.
{218910}{218970}Place your bets.
{219003}{219123}- Jules. Mm-hmm.|- Cards, please.
{219129}{219159}Vincent.
{219316}{219376}Jimmie.
{219410}{219470}Bonnie. Mm-hmm.
{219629}{219719}It's thirty minutes away.|I'll be there in ten.
{220222}{220312}You're... Jimmie, right ?|This is your house ?
{220316}{220436}- It sure is.|- I'm Winston Wolf. I solve problems.
{220441}{220531}- Good. We got one.|- So I heard. May I come in ?
{220535}{220595}Uh, yeah. Please do.
{220598}{220688}You must be Jules.|Which would make you... Vincent.
{220692}{220782}Let's get down|to brass tacks, gentlemen.
{220786}{220846}If I was informed correctly, the clock|is ticking. Is that right, Jimmie ?
{220848}{220908}Uh, one hundred percent.
{220911}{221030}- Your wife Bonnie comes home|at 9:30 in the a.m., correct ?
{221035}{221185}I was led to believe if she|comes home and finds us here,
{221191}{221311}- She wouldn't at that.|- That gives us 40 minutes
{221316}{221406}which, if you do what I say,|when I say it, should be plenty.
{221410}{221530}Now, you got a corpse|in a car, minus a head,
{221786}{221846}- Jimmie.|- Uh-huh.
{221848}{221938}Do me a favor, will ya ? Thought I|smelled some coffee back there.
{221942}{222031}- Would you make me a cup ?|- Uh, yeah, sure.
{222097}{222187}Oh, uh, um,|how do you take it ?
{222191}{222251}Lotsa cream, lotsa sugar.
{222316}{222406}About the car, is there anything|I need to know ? Does it stall ?
{222410}{222530}Does it smoke ? Does it make|a lot of noise ? ls there gas in it ?
{222535}{222625}- Aside from how it looks,|the car's cool.
{222629}{222719}Don't get me on the road and I find out|the brake lights don't work.
{222723}{222843}- As far as I know,|the motherfucker's tip-top.
{222848}{222908}Let's go back|to the kitchen.
{223097}{223187}- Here you go, Mr. Wolf.|- Thank you, Jimmie.
{223316}{223376}Mmm.
{223410}{223470}Okay, first thing.|You two.
{223473}{223563}Take the body,|stick it in the trunk.
{223567}{223657}This looks to be|a pretty domesticated house.
{223660}{223780}- That would lead me to believe|you got cleansers and shit.
{223786}{223876}Good. What I need you two fellas to do|is take those cleaning products...
{223879}{223999}and clean the inside of the car--|I'm talkin' fast, fast, fast.
{224005}{224124}Go in the back seat, scoop up all|those little pieces of brain and skull.
{224129}{224219}Get it out of there.|Wipe down the upholstery.
{224222}{224282}It don't need to be spick-and-span.|You don't need to eat off it.
{224316}{224436}Just give it a good once-over.|What you need to take care of
{224441}{224561}The pools of blood that have collected,|you gotta soak that shit up.
{224567}{224627}We need to raid|your linen closet.
{224629}{224719}I need blankets,|I need comforters, quilts, bedspreads.
{224723}{224843}The thicker the better,|the darker the better.
{224848}{224998}We'll need to camouflage the front seat|and back seat and floorboards...
{225005}{225065}with quilts and blankets,
{225067}{225186}so if a cop starts stickin'|his big snout in the car,
{225191}{225251}but at a glance the car|will appear to be normal.
{225254}{225314}Jimmie, lead the way.|Boys, get to work.
{225316}{225376}"Please" would be nice.
{225441}{225501}- Come again ?|- I said, a "please" would be nice.
{225567}{225687}Get it straight, buster.|I'm not here to say please.
{225754}{225814}And if self-preservation|is an instinct you possess,
{225817}{225907}you'd better fuckin' do it|and do it quick.
{225911}{226031}I'm here to help. If my help's|not appreciated, lotsa luck, gentlemen.
{226036}{226126}No, Mr. Wolf, it ain't like that;|your help is definitely appreciated.
{226130}{226219}Mr. Wolf, listen. I don't|mean disrespect, okay ? I respect you.
{226222}{226312}I just don't like people|barkin' orders at me.
{226316}{226406}If I'm curt with you,|it's because time is a factor.
{226410}{226530}I think fast, I talk fast,|and I need you guys to act fast
{226535}{226625}So pretty please, with sugar on top,|clean the fuckin' car.
{226786}{226876}Don't be lookin' at me like that,|all right ? I can feel your look.
{226973}{227033}It's a 1974 Chevy Nova.
{227098}{227158}Green.
{227222}{227312}Nothin' except for|the mess inside.
{227379}{227439}Mmm, about 20 minutes.
{227473}{227533}Nobody who'll be missed.
{227598}{227688}You're a good man, Joe.|Thanks a bunch.
{227723}{227783}- How we comin', Jimmie ?|- Pretty good.
{227786}{227876}- I got it all here, but, uh,
{227879}{227999}- Mr. Wolf,|you gotta understand something.
{228005}{228095}Okay. You gotta|understand something, uh, Winston.
{228098}{228158}Uh-- Uh, no,|thank you.
{228161}{228250}Uh, this is|our best linen here,
{228254}{228344}and it's, uh--|it was a wedding present...
{228348}{228408}from my Uncle Conrad|and my Aunt Ginny.
{228410}{228560}- They're not with us anymore.|I wanna help--
{228567}{228627}- If you don't mind.|- No, no, please. Go ahead.
{228692}{228842}Your Uncle Conrad and Aunt Ginny,|were they millionaires ?
{228879}{228939}No.
{228942}{229002}Well, your Uncle Marsellus is.
{229005}{229095}And I'm positive that if|Uncle Conrad and Aunt...
{229098}{229188}- Ginny.|- Ginny were here,
{229192}{229311}they would furnish you|with a whole bedroom set,
{229316}{229406}which your Uncle Marsellus|is more than happy to do.
{229535}{229655}I like oak myself.|That's what I have in my bedroom.
{229692}{229752}How about you, Jimmie ?
{229786}{229846}You an oak man ?
{229879}{229939}Oak's nice.
{230098}{230218}Oh, man, I will never|forgive your ass for this shit.
{230224}{230284}This is some fucked-up,|repugnant shit.
{230286}{230405}Jules, did you ever hear the philosophy|that once a man admits he is wrong...
{230410}{230470}that he is immediately forgiven|for all wrongdoings ?
{230473}{230563}Get the fuck out my face|with that shit !
{230567}{230657}The motherfucker that said|that shit never had to pick up
{230660}{230780}- on account of your dumb ass.|- I got a threshold, Jules,
{230786}{230876}Right now, I'm a fuckin' race car,|and you got me in the red.
{230879}{230999}I'm just sayin' it's fuckin' dangerous|to have a race car in the fuckin' red.
{231005}{231065}That's all.|I could blow.
{231067}{231127}- Oh, you ready to blow ?|- Yeah.
{231130}{231190}Well, I'm a mushroom-cloud-layin'|motherfucker, motherfucker.
{231192}{231282}Every time my fingers touch brain,|I'm Superfly T.N.T.
{231286}{231345}I'm the Guns of the Navarone.
{231348}{231438}In fact, what the fuck|am I doin' in the back ?
{231441}{231531}You're the motherfucker should be on|brain detail ! We're fuckin' switchin'.
{231535}{231625}I'm washin' windows, and you're|pickin' up this nigger's skull !
{231911}{231971}Fine job, gentlemen.
{232005}{232065}You may get out of this yet.
{232098}{232158}I can't believe|this is the same car.
{232161}{232251}Well, let's not start suckin'|each other's dicks quite yet.
{232255}{232375}Phase one is complete-- Clean the car--|which moves us right along to Phase two:
{232380}{232439}Clean you two.
{232473}{232533}Strip.
{232535}{232655}- All the way ?|- To your bare ass.
{232660}{232750}Quickly, gentlemen.|We got about 15 minutes...
{232754}{232814}before Jimmie's better half|comes pulling into the driveway.
{232848}{232908}Goddamn, this morning air|is some chilly shit.
{232911}{232971}Are you sure this is|absolutely necessary ?
{232973}{233033}- You know what you two look like ?|- What ?
{233036}{233156}Like a couple of guys|who just blew off somebody's head.
{233161}{233251}Strippin' off those bloody rags|is absolutely necessary.
{233380}{233439}Toss 'em in Jimmie's garbage bag.
{233442}{233592}Don't do nothin' stupid,|like leavin' this shit out front
{233598}{233718}Don't worry, we're taking it with us.|Jim, the soap.
{233754}{233814}- Vincent.|- Okay, gentlemen.
{233817}{233907}You both been to County before,|I'm sure. Here it comes.
{233911}{234001}- Goddamn ! The water's fuckin' cold !|- Yo ! Yo ! Yo !
{234005}{234095}Better you than me, gentlemen.
{234130}{234190}- Don't be afraid of the soap.|Spread it around.
{234192}{234282}- Get 'em there a little bit.|Vincent's hair.
{234286}{234376}- Come on. Do it, goddamn it ! Do it !|- Uh, um--
{234411}{234470}Towel.
{234786}{234876} You're dry enough.|Toss 'em their clothes.
{234879}{234969}Perfect.
{234973}{235093}Perfect. We couldn't have|planned this better.
{235098}{235158}You guys look like--
{235161}{235221}What do they look like,|Jimmie ?
{235224}{235314}- Dorks. They look like|a couple of dorks.
{235349}{235439}- Ha-ha-ha. They're your|clothes, motherfucker.
{235443}{235532}Come on, gentlemen.|We're laughing our way
{235535}{235565}Don't make me beg.
{235661}{235781}Okay, gentlemen, let's get|our rules of the road straight.
{235786}{235876}We're going to a place|called Monster Joe's Truck and Tow.
{235879}{235969}Monster Joe and his daughter Raquel|are sympathetic to our dilemma.
{235973}{236033}The place is North Hollywood,
{236036}{236156}so a few twists and turns aside,|we'll be goin' up Hollywood Way.
{236161}{236251}Now, I'll drive the tainted car.|Jules, you ride with me.
{236286}{236346}Vincent, you follow|in my Acura.
{236349}{236469}Now, if we come across the path|of any John Q. Laws,
{236474}{236563}- nobody does a fuckin' thing|'til I do something.
{236567}{236657}- What did I say ?|- Don't do shit unless.
{236661}{236721}- Unless what ?|- Unless you do it first.
{236723}{236813}Spoken like a true prodigy.
{236817}{236907}How about you, Lash LaRue ?|Can you keep your spurs
{236911}{237031}The gun went off. I don't know why.|I'm cool. I promise you.
{237036}{237126}Fair enough. Now, I drive real|fuckin' fast, so keep up.
{237130}{237190}If get my car back|any different than I gave it,
{237192}{237282}Monster Joe's gonna be|disposing of two bodies.
{237411}{237471}Outta my way, Rex.
{237505}{237565}- We cool ?|- Like it never happened.
{237598}{237688}- All right.|- Boys, this is Raquel.
{237692}{237782}Someday all this will be hers.
{237786}{237876}Hi. So, what's|with the outfits ?
{237880}{237970}- You guys going to|a volleyball game or something ?
{237973}{238033}I'm takin' milady|out for breakfast.
{238036}{238126}Maybe I could drop you two off.|Where do you live ?
{238130}{238160}- Redondo.|- Inglewood.
{238161}{238281}It's--|It's your future. I--
{238286}{238346}I see a--|a cab ride.
{238380}{238440}Move outta the sticks, fellas.|Say good night, Raquel.
{238443}{238533}- Good night, Raquel.|- I'll see you guys around.
{238536}{238626}Stay outta trouble,|you crazy kids.
{238630}{238719}Mr. Wolf, I just wanna tell you it was|a real pleasure watching you work.
{238754}{238814}Yeah, really.|And thank you very much, Mr. Wolf.
{238817}{238877}Call me Winston.
{238942}{239032}- You see that, young lady ? Respect.
{239036}{239156}- Respect for one's elders|shows character.
{239161}{239281}- Because you are a character|doesn't mean that you have character.
{239474}{239564}- Wanna share a cab ?
{239568}{239687}- I'd go for some breakfast.|Feel like havin' breakfast with me ?
{239692}{239782}Cool.
{239911}{240001}I don't know why, I just thought|he'd be European or something.
{240005}{240095}- Yeah, he's about as European|as fuckin' English Bob.
{240099}{240159}- But was he cool or what ?|- Thank you.
{240161}{240251}Totally fuckin' cool,|in control.
{240255}{240375}Didn't even really get pissed when you|were fuckin' with him; I was amazed.
{240380}{240440}- Want some bacon ?
{240443}{240503}No, man, I don't eat pork.
{240505}{240625}- Are you Jewish ?|- I ain't Jewish; I just don't
{240630}{240690}- Why not ?|- Pigs are filthy animals.
{240693}{240752}I don't eat filthy animals.
{240754}{240874}Yeah, but bacon tastes good.|Pork chops taste good.
{240880}{240970}Sewer rat may taste like pumpkin pie,|but I'd never know...
{240973}{241033}'cause I wouldn't eat|the filthy motherfuckers.
{241036}{241126}Pigs sleep and root in shit.|That's a filthy animal.
{241130}{241250}I ain't eatin' nothin' ain't got|sense enough to disregard its own feces.
{241255}{241375}- What about a dog ?|Dog eats its own feces.
{241380}{241500}Yeah, but do you consider|a dog to be a filthy animal ?
{241505}{241595}I wouldn't go so far|as to call a dog filthy,
{241599}{241629}but they're definitely dirty.
{241662}{241752}- But a dog's got personality.|Personality goes a long way.
{241786}{241876}if a pig had a better personality,|he would cease to be a filthy animal.
{241880}{242000}- Is that true ?|- We'd have to be talkin' about
{242005}{242125}I mean, he'd have to be|ten times more charming than
{242286}{242346}Oh, man, that's good.
{242349}{242469}That's good, man.|You're startin' to lighten up.
{242474}{242564}You've been sittin' there,|all serious and shit.
{242568}{242628}- I just been sittin' here, thinkin'.|- About what ?
{242630}{242720}- About the miracle we witnessed.|- Miracle you witnessed.
{242724}{242813}- I witnessed a freak occurrence.|- What is a miracle, Vincent ?
{242880}{242970}- Act of God.|- And what's an act of God ?
{243067}{243187}When, um, God makes|the impossible possible.
{243224}{243284}But this morning...
{243286}{243376}- I don't think qualifies.|- Hey, Vincent.
{243380}{243470}See, that shit don't matter.|You're judging this shit the wrong way.
{243474}{243624}It could be God stopped the bullets,|changed Coke to Pepsi,
{243630}{243720}You don't judge shit like this|based on merit.
{243724}{243784}Now, whether or not|what we experienced...
{243787}{243876}was an according-to-Hoyle miracle|is insignificant.
{243880}{244000}But what is significant is,|I felt the touch of God.
{244005}{244065}God got involved.
{244067}{244127}But why ?
{244130}{244220}Well, that's what's fuckin' with me:|I don't know why.
{244224}{244314}- But I can't go back to sleep.|- You're serious.
{244318}{244378}You're really thinkin'|about quittin'.
{244380}{244440}- For life ? Most definitely.|- Yeah.
{244443}{244533}Fuck.|What you gonna do then ?
{244599}{244719}Well, that's what I been|sitting here contemplating.
{244724}{244814}First I'm gonna deliver|this case to Marsellus.
{244818}{244907}Then, basically, I'm just|gonna walk the Earth.
{244911}{245031}- What you mean, "walk the Earth" ?|- Like Caine in Kung Fu.
{245036}{245126}Walk from place to place,|meet people, get in adventures.
{245130}{245190}And how long do you intend|to walk the Earth ?
{245192}{245282}- 'Til God puts me|where He wants me to be.
{245286}{245436}- If it takes forever,|then I'll walk forever.
{245443}{245533}I'll just be Jules, Vincent.|No more, no less.
{245568}{245598}No, Jules,|you decided to be a bum,
{245599}{245719}just like all those pieces of shit|out there who beg for change,
{245724}{245814}who sleep in garbage bins,|eat what I throw away.
{245818}{245878}They got a name for that, Jules.|It's called a bum.
{245881}{246000}And without a job,|a residence or legal tender,
{246005}{246065}You're gonna be|a fuckin' bum.
{246067}{246157}Look, my friend,|this is just where you and I differ.
{246161}{246251}Garçon ! Coffee !
{246255}{246375}Jules, look, what happened this morning,|man, I agree it was peculiar.
{246380}{246470}- But water into wine, l--|- All shapes and sizes, Vincent.
{246474}{246564}- Don't fuckin' talk|to me that way, man.
{246568}{246658}then you should cease|asking scary questions.
{246724}{246784}I'm gonna take a shit.
{246881}{247000}Let me ask you something.
{247005}{247065}When did you make this decision ?|When you were sittin' there
{247067}{247187}Yeah. I was sittin' here|eatin' my muffin, drinkin' my coffee,
{247192}{247252}replayin' the incident|in my head,
{247255}{247345}when I had what alcoholics refer to|as a moment of clarity.
{247349}{247439}Fuck. To be continued.
{247818}{247908}- I love you, Pumpkin.|- I love you, Honey Bunny.
{247943}{248032}- Everybody be cool !|This is a robbery !
{248036}{248186}Any one of you fucking pricks move,|and I'll execute every one
{248192}{248282}- You got that ?|You just be quiet over there !
{248286}{248376}Get on the fuckin'--|Get the fuck down !
{248380}{248530}You're in a blind spot.|Take your dames over to that booth,
{248537}{248657}- Mexicans, out of|the fucking kitchen !
{248662}{248752}What the fuck are you doing,|you fucking yuppie ? Get down !
{248756}{248846}- Get down !|- Throw those bags !
{248849}{248909}- Fucking move ! Move !
{248912}{248972}- Move ! Get the fuck--
{249006}{249065}Get down on the fucking floor !
{249067}{249127}Grandpa ! Down !
{249130}{249250}I'm the manager here, and there's|no problem. No problem at all.
{249255}{249345}- You gonna give me a problem ?|- No, sir, I'm not.
{249349}{249439}Thought you said you were gonna|give me a fucking problem !
{249443}{249593}- I think we got|a hero here, Honey Bunny.
{249599}{249659}- I am not a hero.
{249662}{249752}- I'm just a coffee shop manager.|- Get the fuck down !
{249756}{249816}The restaurant's ours !
{249818}{249908}- Just take whatever you want.
{249912}{249942}- You talk to the customers.|- Yeah.
{249974}{250064}You tell them to be fucking cool|and everything will be over.
{250068}{250097}- You understand me ?|- Yes !
{250192}{250222}Listen, everybody.
{250255}{250285}Be calm, cooperate,
{250318}{250378}and this'll all be over|in a minute !
{250380}{250440}Get the fuck down !|Well done.
{250818}{250908}All right, now, people, gonna|come around and collect your wallets !
{250912}{251032}You don't fucking talk. You just|throw 'em in the bag ! Are we clear ?
{251037}{251097}I said, are we fucking clear ?
{251100}{251189}Good !|Now, wallets out !
{251192}{251282} That's it.|Get the fuck down. In the bag.
{251286}{251376}- In the fucking bag !|- I don't
{251380}{251440}In the bag.
{251443}{251533}What am I waiting for ?|ln the fucking bag.
{251537}{251627}Laura. Laura. Tips.|In the bag.
{251630}{251690}- Is that a cellular phone ?|- Yeah.
{251693}{251753}In the fucking bag.
{251818}{251908}Tidy up, tidy up, that's it.|Now get the fuck down on the floor.
{251912}{251972}In the bag.|In the bag.
{252349}{252409}In the bag.
{252849}{252939}- What's in the case ?|- My boss's dirty laundry.
{252943}{253033}- Your boss makes you do his laundry ?|- When he wants it clean.
{253037}{253097}- Sounds like a shit job.|- Funny, I was thinkin' the same thing.
{253100}{253190}- Open it.|- 'Fraid I can't do that.
{253255}{253315}- I didn't hear you.|- Yes, you did.
{253349}{253439}What's going on ?
{253443}{253533}- Looks like we got|a vigilante in our midst.
{253537}{253657}I hate to shatter your ego,|but this ain't the first time
{253662}{253752}- If you don't take your hand off|that case, it'll be your last.
{253756}{253846}You'll get us all killed ! Give 'em|what you got and get 'em outta here !
{253849}{253969}Shut the fuck up, fat man ! This ain't|none of your goddamn business !
{253975}{254035}Be cool, Honey Bunny, be cool.
{254037}{254097}No problem.|I got it under control.
{254162}{254222}Now, I'm gonna count to three.
{254256}{254375}If you don't open that case,|I'm gonna unload in your fucking face.
{254505}{254565}We clear ?
{254662}{254722}One.
{254787}{254847}Two.
{254849}{254909}- Three.|- Okay, Ringo.
{254912}{254972}You win.
{254975}{255035}It's yours.
{255162}{255252}- Open it.
{255349}{255409}Hey, what is it ?
{255411}{255501}What is it ?
{255505}{255565}Is that what I think it is ?
{255568}{255658}Mm-hmm.
{255693}{255753}It's beautiful.
{255787}{255847}Goddamn it, what is it ?
{255881}{255971}You let him go !|You let him go !
{255975}{256065}- Let go of him, or I'm gonna kill you !|- Tell that bitch to be cool.
{256068}{256158}- Say, "Bitch, be cool !"|Say, "Bitch, be cool !"
{256162}{256252}- Tell that bitch to chill !|- You're gonna die so fuckin' bad !
{256256}{256345}- Chill that fuckin' bitch out !|- Chill out, Honey Bunny !
{256349}{256379}- Let go of him !|- Chill out, Honey Bunny !
{256380}{256470}- Now, promise her|it's gonna be all right !
{256474}{256534}- Tell her to chill !|- Chill out, Honey Bunny !
{256537}{256597}- Now tell me her name.|- Yolanda.
{256599}{256689}All right, now, Yolanda, we're not|gonna do anything stupid, are we ?
{256693}{256783}- Don't you hurt him !|- Nobody's gonna hurt anybody !
{256787}{256907}We're all gonna be like three little|Fonzies here. And what's Fonzie like ?
{256912}{257002}- Come on, Yolanda !|What's Fonzie like ?
{257006}{257066}- What ?|- Cool.
{257068}{257158}Correctamundo.|And that's what we're gonna be.
{257162}{257222}We're gonna be cool.
{257225}{257375}Now, Ringo,|I'm gonna count to three.
{257381}{257440}And when I count three,
{257443}{257533}I want you to|let go of your gun,
{257537}{257627}put your palms flat on the table|and sit your ass down.
{257662}{257722}And when you do it,
{257724}{257784}you do it cool.
{257787}{257847}You ready ?
{257849}{257909}One,
{257943}{258003}two,
{258006}{258066}three.
{258256}{258346}- Okay, now you let him go !|- Yolanda !
{258350}{258469}I thought you were gonna|be cool. Now, when you yell
{258474}{258534}When I get nervous,|I get scared.
{258537}{258657}When motherfuckers get scared,|that's when motherfuckers
{258693}{258813}Just know, you hurt him, you die.
{258818}{258908}Well, that seems to be|the situation.
{258912}{258972}But I don't want that.
{258975}{259035}And you don't want that.
{259037}{259097}And Ringo here definitely|doesn't want that.
{259131}{259191}So let's see what we can do.
{259256}{259346}Now... here's the situation.
{259350}{259469}Normally both your asses would be|dead as fuckin' fried chicken,
{259474}{259564}but you happened to pull this shit|while I'm in a transitional period,
{259568}{259658}and I don't wanna kill you;|I wanna help you.
{259662}{259782}But I can't give you this case,|'cause it don't belong to me.
{259787}{259877}Besides, I been through too much shit|over this case this morning...
{259881}{259971}to just hand it over|to your dumb ass.
{259975}{260005}- Vincent !
{260006}{260096}- Be cool ! Yolanda, it's cool, baby.|- Get back !
{260100}{260190}It's cool !|We still just talkin'.
{260194}{260314}- Come on. Point the gun at me.|Point the gun at me. There you go.
{260319}{260379}Now, Vincent, you just hang back...
{260381}{260441}and don't do|a goddamn thing.
{260444}{260504}Tell her it's still cool.
{260506}{260595}- It's still cool, Honey Bunny.|- How we doin', baby ?
{260630}{260720}I-- I gotta go pee.
{260724}{260784}I wanna go home.
{260787}{260877}Hang in there, baby. I'm proud of you.|And Ringo's proud of you.
{260881}{260971}It's almost over.|Tell her you're proud of her.
{260975}{261065}- I'm proud of you, Honey Bunny.|- I love you.
{261068}{261158}- I love you too, Honey Bunny.|- Now,
{261162}{261282}I want you to go in that bag|and find my wallet.
{261381}{261471}- Which one is it ?|- It's the one that says
{261912}{262002}That's it.|That's my bad motherfucker.
{262006}{262096}Open it up.|Take out the money.
{262225}{262315}Count it.
{262506}{262566}How much is there ?
{262630}{262690}About 1,500 dollars.
{262693}{262783}Okay, put it in your pocket.|It's yours.
{262787}{262877}Now, with the rest|of those wallets and the register,
{262881}{262941}that makes this a pretty successful|little score, huh ?
{262943}{263063}Jules, you give that fuckin'|nimrod 1,500 dollars, and I'll
{263068}{263158}No, Yolanda ! Yolanda ! He ain't gonna|do a goddamn, motherfuckin' thing !
{263162}{263222}Vince, shut the fuck up !
{263225}{263345}- Shut up !|- Come on, Yolanda. Stay with me, baby.
{263350}{263440}Now, I ain't givin' it|to him, Vincent.
{263444}{263504}I'm buyin' something|for my money.
{263538}{263628}- Wanna know what I'm buyin', Ringo ?|- What ?
{263632}{263781}Your life. I'm givin' you that money|so I don't have to kill your ass.
{263787}{263847}You read the Bible, Ringo ?
{263881}{263941}Not regularly, no.
{263943}{264033}Well, there's this passage|I got memorized.
{264037}{264127}Ezekiel 25:17.
{264131}{264221}"The path of the righteous man|is beset on all sides...
{264225}{264285}by the inequities|of the selfish...
{264287}{264347}and the tyranny of evil men.
{264350}{264440}Blessed is he who,|in the name of charity and good will,
{264444}{264504}shepherds the weak|through the valley of darkness,
{264538}{264628}for he is truly his brother's keeper|and the finder of lost children.
{264663}{264782}And I will strike down upon thee with|great vengeance and furious anger...
{264787}{264877}those who attempt to poison|and destroy My brothers.
{264881}{264971}And you will know|I am the Lord...
{264975}{265065}when I lay My vengeance|upon you."
{265100}{265160}I been sayin' that shit for years,
{265194}{265284}and if you heard it,|that meant your ass.
{265287}{265347}I never gave much thought|to what it meant.
{265381}{265441}I just thought it was some coldblooded|shit to say to a motherfucker...
{265444}{265534}before I popped a cap|in his ass.
{265538}{265628}But I saw some shit this morning|made me think twice.
{265632}{265721}See, now I'm thinkin'|maybe it means...
{265724}{265874}you're the evil man,|and I'm the righteous man,
{265881}{265971}and Mr. 9-millimeter here,|he's the shepherd...
{265975}{266065}protecting my righteous ass|in the valley of darkness.
{266068}{266128}Or it could mean...
{266131}{266221}you're the righteous man,|and I'm the shepherd,
{266225}{266345}and it's the world|that's evil and selfish.
{266350}{266410}Now, I'd like that.
{266444}{266504}But that shit|ain't the truth.
{266506}{266566}The truth is,
{266600}{266660}you're the weak...
{266694}{266813}and I'm the tyranny|of evil men.
{266850}{266910}But I'm tryin', Ringo.
{266943}{267033}I'm tryin' real hard...
{267037}{267097}to be the shepherd.
{267569}{267629}Go.
{268162}{268222}I think we should be|leaving now.
{268225}{268315}- Yeah, that's probably a good idea.
